### ISSUE TITLE
Support detecting request body

### ISSUE THREAD

**Issue by clue** [reactphp/http#104]
Proper detection of request message bodies requires:
* Content-Length
* Chunked transfer encoding (#96)
* Empty bodies for certain requests

See https://tools.ietf.org/html/rfc7230#section-3.3

This means that we should take these into account and only emit `data` events for what is actually part of the given request and then emit an `end` and `close` event.

This is also a prerequisite for #39.

**Comment by WyriHaximus** [comment]
While seeing all the prerequisites are met, doesn't this make more sense to come in `0.8`?

**Comment by clue** [comment]
This PR only handles *detecting* the message body, i.e. emitting streaming `data`, `end`, `error` and `close` events. Afaict this is not handled for all cases yet (requests with implicit message lengths). Once everything is completed, this should be released as v0.6.0.

This ticket does not handle parsing this message body, this is left up for #105. Parsing the body relies on detecting its length first (this ticket) and likely also on adding a proper interface first (#28), so this is currently planned for the v0.8.0 release.

**Comment by clue** [comment]
Closed via #116, #129, #130, #136 and #137. Example added via #139.
