### ISSUE TITLE
PSR-7 Message Implementation: ringcentral vs guzzle

### ISSUE THREAD

**Issue by andig** [reactphp/http#111]
I've recently started noticing my build to fail when testing for lowest version constraint on its dependencies. Turns our this is caused by a conflict between `reactphp/http@dev-master` and `guzzlehttp/guzzle@6.2.2`:

Error:

	PHP Fatal error:  Cannot redeclare GuzzleHttp\Psr7\str() (previously declared in /home/travis/build/volkszaehler/volkszaehler.org/vendor/guzzlehttp/psr7/src/functions.php:17) in /home/travis/build/volkszaehler/volkszaehler.org/vendor/ringcentral/psr7/src/functions.php on line 39
	Fatal error: Cannot redeclare GuzzleHttp\Psr7\str() (previously declared in /home/travis/build/volkszaehler/volkszaehler.org/vendor/guzzlehttp/psr7/src/functions.php:17) in /home/travis/build/volkszaehler/volkszaehler.org/vendor/ringcentral/psr7/src/functions.php on line 39

Conflicting versions:

	Installing guzzlehttp/psr7 (1.0.0) Loading from cache
	Installing ringcentral/psr7 (1.0.0) Downloading: 100%

Working versions:

	Installing ringcentral/psr7 (1.2.1) Downloading: 100%
	Installing guzzlehttp/psr7 (1.3.1) Loading from cache

As of 6.0, guzzle requires `guzzlehttp/psr7:~1.0` just as `reactphp/http` requires `ringcentral/psr7:~1.0`. Conflict seems to be resolved as of `ringcentral/psr7:^1.2` independently from the guzzlehttp version (tested starting at 6.0).

I'd like to propose to either switch to `guzzlehttp/psr7` or upgrade `ringcentral/psr7:^1.2` to avoid this conflict (couldn't find out which benefits ringcentral has- definitely less often used according to packagist). 

Of course it's possible to work around this on client side but... time consuming :/

**Update** realized ringcentral is needed for PHP 5.3 compatibility (brrrh). So upgrading to 1.2 would be the suggested approach. On the other hand `react/eventloop` already demands 5.4 so 5.3 support is out of question anyway? `guzzlehttp/psr7` is on php 5.4 as of v1.0.

**Comment by clue** [comment]
Thanks for bringing this to our attention and I agree it's well worth fixing! :+1: 

Do you feel like filing a PR to address this? :+1:

See also #101 for some background on why this was introduced and how we support legacy versions.

**Comment by WyriHaximus** [comment]
Upping the targeting to `ringcentral/psr7:^1.2` should do the trick 👍 

@clue FYI this is why I test like this https://blog.wyrihaximus.net/2015/06/test-lowest-current-and-highest-possible-on-travis/ maybe we could discuss testing with one job against `composer update --prefer-lowest`

**Comment by andig** [comment]
I would but I'm really confused where to go. 1.2 is the easy way. But as 5.3 support- at least when using eventloop- is out of question anyway- why keep it?

**Comment by clue** [comment]
This component does not have an dependency on react/event-loop at all. Our other dependencies do in fact require react/event-loop, but support both v0.3 and v0.4, so I'm not exactly sure what you're asking here? :-)

**Comment by andig** [comment]
I'll file a pr for 1.2 plus one for testing lowest/highest dependencies

**Comment by WyriHaximus** [comment]
Lowest would do as we don't commit a lock file and automatically use the highest available 😄

**Comment by clue** [comment]
Closed via #113
