### ISSUE TITLE
Chrome only: Emits additional `error` events for HTTPS only (Unable to complete SSL/TLS handshake)

### ISSUE THREAD

**Issue by bassim** [reactphp/http#134]
When i run the 02-hello-world-https.php example, it does work (seeing "hello world" in a browser).

But I am also seeing this error:

```
php examples/02-hello-world-https.php 
Listening on https://0.0.0.0:8443
exception 'UnexpectedValueException' with message 'Unable to complete SSL/TLS handshake: ' in /Users/*********/Projects/http/vendor/react/socket/src/StreamEncryption.php:112
Stack trace:
#0 /Users/*********/Projects/http/vendor/react/socket/src/StreamEncryption.php(78): React\Socket\StreamEncryption->toggleCrypto(Resource id #28, Object(React\Promise\Deferred), true)
#1 [internal function]: React\Socket\StreamEncryption->React\Socket\{closure}(Resource id #28, Object(React\EventLoop\StreamSelectLoop))
#2 /Users/*********/Projects/http/vendor/react/event-loop/src/StreamSelectLoop.php(232): call_user_func(Object(Closure), Resource id #28, Object(React\EventLoop\StreamSelectLoop))
#3 /Users/*********/Projects/http/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#4 /Users/*********/Projects/http/examples/02-hello-world-https.php(29): React\EventLoop\StreamSelectLoop->run()
#5 {main}exception 'UnexpectedValueException' with message 'Unable to complete SSL/TLS handshake: ' in /Users/*********/Projects/http/vendor/react/socket/src/StreamEncryption.php:112
Stack trace:
#0 /Users/*********/Projects/http/vendor/react/socket/src/StreamEncryption.php(78): React\Socket\StreamEncryption->toggleCrypto(Resource id #55, Object(React\Promise\Deferred), true)
#1 [internal function]: React\Socket\StreamEncryption->React\Socket\{closure}(Resource id #55, Object(React\EventLoop\StreamSelectLoop))
#2 /Users/*********/Projects/http/vendor/react/event-loop/src/StreamSelectLoop.php(232): call_user_func(Object(Closure), Resource id #55, Object(React\EventLoop\StreamSelectLoop))
#3 /Users/*********/Projects/http/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#4 /Users/*********/Projects/http/examples/02-hello-world-https.php(29): React\EventLoop\StreamSelectLoop->run()
#5 {main}
```

Also I think the response time might be low side.

I did have to include a cafile in the example code

```
$loop = Factory::create();
$socket = new Server(isset($argv[1]) ? $argv[1] : '0.0.0.0:8443', $loop);
$socket = new SecureServer($socket, $loop, array(
    'local_cert' => $argv[2]. '/bin/combined.pem',
    'cafile' => $argv[2]. '/bin/intermediate.pem',
));
```

**Comment by clue** [comment]
Unfortunately, I can't reproduce this locally.

Can you provide a gist to reproduce this? Such as, where does this error come from, why is this printed to your console, which client are you using?

**Comment by bassim** [comment]
I could try setting up a gist I guess.

The error is displayed on the console when unqouting this line:

https://github.com/reactphp/http/blob/master/examples/02-hello-world-https.php#L23

and running 'php examples/02-hello-world-https.php 0.0.0.0:8443 /path/to/certificates'

Which client I am using? What do you mean exactly?

**Comment by WyriHaximus** [comment]
> Which client I am using? What do you mean exactly?

What browser and which version are you using to connect to the HTTPS server?

**Comment by bassim** [comment]
Yes! I only get the error by using:

Google Chrome Version 56.0.2924.87 (64-bit)

Cannot repro on firefox, safari. Response time in these browsers seem better also

**Comment by clue** [comment]
Not sure what's going on here as the TLS handshake appears to fail but the error message is apparently empty. Could your browser perhaps be terminating the connection before the TLS handshake completes?

Can others reproduce this or does this only happen on certain configurations?

Also, is there really anything that we should fix here? The `error` event is emitted by the Socket component which means that an incoming TLS connection did not succeed (this is documented and expected behavior). Does this really cause any issues here?

**Comment by bassim** [comment]
Ok, I have tested again on my chrome with using charles web debugging proxy (allowing it to be man in the middle). If i load page once, I am seeing 4 requests in charles. first 2 attempts fail, 3 succeeds, and 4th fails again.

Including some screenshot of charles:

![screen shot 2017-03-01 at 13 55 35](https://cloud.githubusercontent.com/assets/748403/23460705/eb0332a8-fe86-11e6-8225-86988a9a472d.png)
![screen shot 2017-03-01 at 13 55 17](https://cloud.githubusercontent.com/assets/748403/23460707/ed8261c0-fe86-11e6-8924-0c3c513e9b08.png)

Safari and Firefox only need 1 request to see the 'Hello World' text

**Comment by akadlec** [comment]
So i have simillar issue. Chrome is unable to finish handshake. MS Edge too. Only FireFox is working great
```

**Comment by kelunik** [comment]
@akadlec @bassim Do you use `"local_cert"` with key + certificate + certificate chain in one file?

**Comment by bassim** [comment]
@kelunik sorry for the late reply. The answer is no.

I am using this:

```
'local_cert' => __DIR__ . '/combined.pem',
'cafile' => __DIR__ . '/intermediate.pem',

```

Where combined contains the private key + certificate

**Comment by clue** [comment]
So far we've not been able to reproduce this (afaict).

Can anybody provide us with a simple gist on how to reproduce this and what your certificate setup look like, possibly with the required `openssl` commands etc.? Thanks!

**Comment by kelunik** [comment]
@bassim All intermediates should be appended to `combined.pem` then, `"cafile"` is used for peer verification.

**Comment by akadlec** [comment]
I am using certificate generated by LetsEncrypt this way:
```

**Comment by clue** [comment]
Ping @bassim and @akadlec, can you update the status here, does the problem persist or did you mange to resolve this in the meantime?

So far we've not been able to reproduce this (afaict).

If this problem persists, can anybody provide us with a simple gist on how to reproduce this and what your certificate setup look like, possibly with the required openssl commands etc.? Thanks!

**Comment by akadlec** [comment]
For me i fixed it with proxy. Mabye it is a lets encrypt issue, right now i'm without time to more dig into this problem.

**Comment by kelunik** [comment]
@akadlec Could you give local_cert => fullchain.pem / local_pk => key.pem a try without further digging?

**Comment by clue** [comment]
Closing this due to a lack of feedback, as we can not reproduce this. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by woytam** [comment]
I have exactly same problem with Chrome and solution was adding `verify_peer` and `verify_peer_name` set to `false` in tls context.
```
$socket = new \React\Socket\Server('tls://0.0.0.0:8080', $loop, array(
	'tls' => array(
		'local_cert' => 'fullchain.pem',
		'local_pk' => 'privkey.pem',
		'verify_peer' => false,
		'verify_peer_name' => false
	)
));
```
Both `verify_...` are used when using client certificate authentication. In most TLS server like standard HTTPS server it is not used. So I suggest adding this parameters to SecureServer examples.

**Comment by WyriHaximus** [comment]
@woytam we are always to PR's so feel free to create one addressing that

**Comment by woytam** [comment]
PR #333 adds SSL context with `verify_peer` and `verify_peer_name` disabled in examples and code comments.
