### ISSUE TITLE
Use faster pecl_http parser

### ISSUE THREAD

**Issue by cameronjacobson** [reactphp/http#14]
http://devel-m6w6.rhcloud.com/mdref/http/Message/Parser

Not released yet.

It looks like this may be the missing piece to robust public-facing event-driven HTTP/1.1 servers written in PHP.

**Comment by ichiriac** [comment]
Hi,

I've made a pull-request on this, using it from guzzle dirrectly :
https://github.com/reactphp/http/pull/19

**Comment by christoph-kluge** [comment]
Is this feature still requested/required? I did some investigation on the PR and the current code and those changes seem pretty outdated. I would like to contribute here!

**Comment by cboden** [comment]
I was using this parser in Ratchet for the longest time but I came across an issue where it was claiming a completely valid HTTP request (that actually came from a browser) was invalid and refused to parse it. I had to drop support for the PECL extension completely.

**Comment by cameronjacobson** [comment]
Are there any robust, decoupled HTTP parsers in the works for PHP (or already in the ecosystem with traction that I'm unaware of)?  More recently than the above ticket I've been thinking about a couple different things short of building a full PHP extension (or PHP library) to make HTTP parsing sane in PHP.

1) I found a nice HTTP parser extension on GitHub that doesn't appear to require any work to upgrade to use the current NodeJS HTTP parser.  Though I'm not 100% sure how it would perform in an evented environment like ReactPHP.  I doubt there would be any serious bottlenecks, but haven't run any tests to confirm this.

  https://github.com/chobie/php-httpparser

The ticket I submitted to find out status of the project is here:
  https://github.com/chobie/php-httpparser/issues/2

2) I've dug only surface deep but think it might be worth looking into further.  I've been researching the idea of embedding a Golang HTTP service inside a PHP extension.  This would in theory give you HTTP2 as well, and would require minimal maintenance as Golang improves their HTTP parser, and as a nice bonus would support HTTP2 out of the box.

**Comment by clue** [comment]
> Is this feature still requested/required?

This ticket has never gained a lot of traction because it's unclear if parsing the HTTP requests is actually a bottleneck and whether a "faster pecl_http parser" would actually improve this much.

I'd like to get the next release out and believe this has been answered already, so I'm closing this for now. :shipit: 

Please come back and open a PR if you feel this is still needed and we can reconsider this :+1:
