### ISSUE TITLE
Request Draining

### ISSUE THREAD

**Issue by rhclayto** [reactphp/http#145]
I want to restart my React/HTTP server process periodically based on various criteria. Is there a way to make sure that all active connections/requests are finished, & to stop accepting new requests while they are finishing, before I shut down the server process?

The current code looks something like this:

```php
$request->on('end', function () {
  // blah blah blah...
  $response->writeHead($status_code, $output_headers);
  $response->end($returnContent);
  // Auto-recycling of daemon.
  if ($current_memory_usage > $memory_limit || $requests_served > $request_limit || time() >= $time_to_live) {
    $response->close();
    shell_exec('/usr/local/bin/supervisorctl restart daemonchild:' . $pid);
   }
});
```

Currently the shutdown code prevents the request that triggered it from completing, i.e., no data is returned to the client, even though ```$response->end($returnContent);``` is called before the shutdown code. In addition, it seems that any new requests coming in while the server is shutting down will fail as well.

So, is connection draining a possibility?

PS: I have also tried putting the shutdown code in ```$request->on('close', function()});```, but with the same result.

**Comment by clue** [comment]
I'm not entirely convinced this whole approach is very useful, but sure, you can of course end all pending requests/responses and stop accepting new ones.

The `Response` implements `WritableStreamInterface`, so you may want to check out its documentation. Calling `close()` will discard any buffers, so you should probably wait for the `end()` to raise a `close` event and/or apply a timeout here first.

Also, you may want to check out the documentation for `SocketInterface`. Calling `$socket->close()` will cause the server to stop accepting new connections (but will keep existing ones alive). This may or may not be enough to restart a new process on the same port already. As a bonus, I would suggest running multiple processes in parallel here and sharing the same address.

I hope this helps :+1:

**Comment by rhclayto** [comment]
Thanks for the guidance. I'm interested, though, in what in your opinion are the shortcomings of this approach.

**Comment by clue** [comment]
I'm leaning towards "if it ain't broken, don't fix it", so if your code works for you, good! :-)

You've provided some more details in your last reply that weren't clear before and I suppose there are many more variables in place that can't really be worked out without an in-depth analysis.

**Comment by rhclayto** [comment]
👍  Thanks!

**Comment by rhclayto** [comment]
Just to add to this in case there's a slim chance anybody ever needs to do something like this, I found a great way using HAProxy:

```php
if (($current_memory_usage >= $memory_limit || $requests_served >= $request_limit || time() >= $time_to_live) && $is_restarting === FALSE) {
      // Tell HAProxy over the stats socket to stop routing new connections to this instance.
      shell_exec("echo 'disable server daemonchild/$dc_name' | /usr/local/bin/socat /var/haproxy/stats.socket stdio");
      // Ten seconds from now, restart this process. The timer is necessary to allow the current requests to finish & to allow HAProxy time to stop routing new requests to the process.
      $loop->addTimer(10, function() use ($pid, $socket, $dc_name) {
        // Close the React socket so that it stops accepting new requests while we're shutting down.
        $socket->close();
        // Tell supervisord to restart this process.
        shell_exec('/usr/local/bin/supervisorctl restart daemonchild:' . $pid);
      });
    }
```

First tell HAProxy to stop accepting new connections, while continuing to allow current connections to finish. Then restart the react server process. When the react server process starts, it sends a corresponding message to HAproxy telling it to begin sending requests to the restarted server. It works excellently.
