### ISSUE TITLE
Request getBody() method

### ISSUE THREAD

**Issue by hariskhaliquecs** [reactphp/http#147]
Hi guys I am trying to implement reactphp with symfony version 2.8 by following this tutorial ( https://gnugat.github.io/2016/04/13/super-speed-sf-react-php.html ).

Symfony request constructor need following parameters 
* Constructor.
*
* @param array           $query      The GET parameters
* @param array           $request    The POST parameters
* @param array           $attributes The request attributes (parameters parsed from the PATH_INFO, ...)
* @param array           $cookies    The COOKIE parameters
* @param array           $files      The FILES parameters
* @param array           $server     The SERVER parameters
* @param string|resource $content    The raw body data

in older version of react we have method 
getBody() and getFile() and two classes RequestParser and MultiPartParser 

I want to ask how I get body content to parse post and FIles to send post and FILES to symfony 2.8.

**Comment by andig** [comment]
You'll need to wait for 0.8 which is scheduled for this month afaik.

**Comment by hariskhaliquecs** [comment]
@andig could you tell me in version I can found that so that I can download package by composer.

**Comment by WyriHaximus** [comment]
@hariskhaliquecs it will come in `v0.8.0` https://github.com/reactphp/http/issues/120

**Comment by clue** [comment]
I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:

**Comment by hariskhaliquecs** [comment]
Where can I found document for reactphp or any tutorial that help me setup reactphp with symfony.

**Comment by andig** [comment]
> Where can I found document for reactphp or any tutorial that help me setup reactphp with symfony.

I would suggest https://github.com/php-pm/php-pm for this purpose
