### ISSUE TITLE
Merge HttpClient component into this component

### ISSUE THREAD

**Issue by clue** [reactphp/http#148]
Here's the current situation:
* This Http component: Event-driven, streaming plaintext HTTP and secure HTTPS server for ReactPHP. 
* HttpClient component: Asynchronous HTTP client library. 

This is not exactly ideal, they share quite a bit of common code.

Also, I believe this situation may be a bit confusing for consumers of this package. In particular our Datagram component provides both client and server side for datagram sockets (UDP).

As such, I'd vote for merging these two components into a single Http component.

**Comment by cebe** [comment]
> they share quite a bit of common code.

Could you point out which code they share? When looking at the code I could not find anything obvious.

**Comment by clue** [comment]
> Could you point out which code they share? When looking at the code I could not find anything obvious.

Good point. You're right in that they currently don't share much code (except for chunked transfer encoding maybe). However, they share quite a bit of *domain knowledge*. In particular, we've had to backport fixes / minor features from this component to the http-client repeatedly.

Also, looking at its roadmap (https://github.com/reactphp/http-client/issues/79) reveals that we plan to implement PSR-7 interfaces (https://github.com/reactphp/http-client/issues/41) also for the http-client. Once this is in, they will share significantly more code.
