### ISSUE TITLE
Retry request on error

### ISSUE THREAD

**Issue by rhclayto** [reactphp/http#149]
I have a React HTTP server that has a persistent connection to a MongoDB server. When the MongoDB server restarts, the React HTTP server still has the old connection in memory. When a request comes in, React gives an http->on('error', ...) error.

I want to listen for this error, correct the MongoDB connection, & resend the request, which will use the new connection & not error out the second time.

I try to do:

```php
 $http->on('error', function (Exception $error) use ($request, $response, $other_variables) {
    $error_message = $error->getMessage();
    // Recover from MongoDB connection errors.
    if (strpos($error_message, 'ailed to send') !== FALSE || strpos($error_message, 'o suitable servers') !== FALSE || strpos($error_message, 'onnection closed') !== FALSE) {
      // Establish new MongoDB connection.
      mongodb();
      // Retry the request.
      daemonchild_finish($request, $response, $other_variables);
    }
  });
```

However, it appears the $request & $response that are available in the other $http listeners are not available in the error listener, for when I pass them into a function to resend the request (the same function I use in the 'end' listener to handle the request/response when there are no errors) I get the following error:

```|Error: Call to a member function writeHead() on null in {closure}()```

That's ```$response->writeHead($status_code, $output_headers);```, so $response is null when I try to pass it into the function, but it's available in the other listeners.

Is there any way to access the request & response objects inside the 'error' listener?

**Comment by legionth** [comment]
I think you are mixing a few things here.

An `error` event will be emitted by the server if **the request** of the client is **invalid**.
A Response object will be emitted via the `request` event, not on an `error` event. If an error occures the `request` event will never be emitted.

I hope this helps.

**Comment by rhclayto** [comment]
It's quite likely I am mixing something up.

However, if the MongoDB server has been restarted, & then a client make a valid request that normally works, & I get an error in the error listener. I log the error in that listener. Why would that be? The error is: ```Failed to send "find" command with database "example": socket error or timeout'```

Thanks for your help.
