### ISSUE TITLE
remoteAddress property not part of PSR-7

### ISSUE THREAD

**Issue by maciejmrozinski** [reactphp/http#153]
Hi,

Just a quick thought about `remoteAddress` property which is added to every request object. Shouldn't we add it through `withAttribute` method? This will be compatible with PSR7, right now it doesn't look that way https://github.com/reactphp/http/blob/master/src/Server.php#L235

**Comment by clue** [comment]
Thanks for spotting and reporting this @maciejmrozinski!

This is something we're aware of and I hear this is something @legionth is currently working on as part of #28 :-) Note that this isn't "incompatible" per se, it's just not part of PSR7 and the server params or attributes would be better suited for this :+1: 

Refs #146, so this only affects the current master branch and has not (and will not) end up in any releases.

**Comment by maciejmrozinski** [comment]
@clue You're right. "Incompatible" is too strong word for this situation. Waiting to see it changed by @legionth then :) thx

**Comment by ssipos90** [comment]
@maciejmrozinski, that class can implement and extend anything, as long as it respects the psr interface.

**Comment by maciejmrozinski** [comment]
Resolved in #160 :)
