### ISSUE TITLE
Add write possibility to HttpBodyStream

### ISSUE THREAD

**Issue by maciejmrozinski** [reactphp/http#171]
Will this be correct if we'll change current `write` method in this way:

old:
```php
public function write($string)
{
    throw new \BadMethodCallException();
}
```

new:
```php
public function write($string)
{
    $this->input->emit('data', [$string]);
    return strlen($string);
}
```
I think it will make `HttpBodyStream` more `compatible` with PSR-7. I'm sure other changes need to be added, but just want to throw an idea.

**Comment by clue** [comment]
There are currently no immediate plans to build this from my end, but I would be really happy to accept PRs :+1: I'm not opposed to this at all, but its implications are currently a bit unclear (how does this compare to the `WritableStreamInterface`, what about `end()` and `close()`?).

This would probably work for the response side, but should not be available on the request side. As an alternative, most request handler callbacks that need writable streaming support can probably easily use a `TroughStream` instead.

**Comment by clue** [comment]
Ping @maciejmrozinski, what's the status here? :+1:

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:
