### ISSUE TITLE
Finish request event

### ISSUE THREAD

**Issue by grachevko** [reactphp/http#176]
Will the ability to execute the code after the response is sent and connection is closed like fastcgi_finish_request in php-fpm?

**Comment by clue** [comment]
```php
$http = new Server($socket, function (ServerRequestInterface $request) use ($loop) {
    $loop->addTimer(0.001, function () {
      echo 'Response has already been sent';
    });
    return new Response(
        200,
        array('Content-Type' => 'text/plain'),
        "Hello World!\n"
    );
});
```

I hope this helps :+1:

**Comment by grachevko** [comment]
@clue just tested and nope. Callback inside timer keep connection and client wait execution. fastcgi_finish_request flush connection and client don't wait.

**Comment by clue** [comment]
I'm not sure I follow what you're trying to achieve and what exactly does not work? Can you provide a gist of the problem you're seeing? :+1:
