### ISSUE TITLE
Add uploaded files to `ServerRequest`

### ISSUE THREAD

**Issue by legionth** [reactphp/http#177]
A uploaded file should be added to the `ServerRequest` object. To check for an uploaded file in the body, the body must be parsed, which is similar to #105. How this should be handled is defined in the docblock of the method in the [PSR-7 ServerRequestInterface](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message.md#321-psrhttpmessageserverrequestinterface)

The [roadmap](https://github.com/reactphp/http/issues/120) shows that this feature is targeted for version v0.8.0.

**Comment by clue** [comment]
Closed via #226
