### ISSUE TITLE
How to set  css , js or images files responses ?

### ISSUE THREAD

**Issue by askuiop** [reactphp/http#186]
How to set css , js or images files responses ?

**Comment by ssipos90** [comment]
Static content should be served by a dedicated HTTP server (nginx, apache) in front of the reactphp application.

However, if the content is generated in your application, then you'd only need to return a response with the appropriate content headers (text/css, application/javascript, image/png, etc) and just give the string as an argument to the request body.

Moreover, if you want to read the file from disk and send it as a response, preferably you'd have to setup a loop that allows async disk I/O and pipe the stream to the response.

**Comment by clue** [comment]
Thanks @ssipos90! I believe this has been answered and I'm closing this for now, please feel free to come back to this ticket with more details if this problem persists and we can reopen this :+1:
