### ISSUE TITLE
Plan to drop PHP 5.x support?

### ISSUE THREAD

**Issue by gsdevme** [reactphp/http#196]
Just wondering what the plan is re: end of life versions of PHP 5.3/4/5, none of which are supported by PHP. I got caught out by the long array syntax on a PR

**Comment by andig** [comment]
I can only repeat that raspberry pi is still on 5.6 as long as stretch-based raspbian has not been released. Don't see any need for versions prior than that though.

**Comment by clue** [comment]
I personally encourage every single user of this library to use PHP7+ for a various reasons (performance, security, support) :+1: 

That being said, how much would be gained by dropping support for older versions? Note that this is BC break which will have the effect that a non-zero number of users will not be able to upgrade anymore. This leaves us with the question which version we should upgrade to?

Our current focus is on releasing a stable v1.0.0 ASAP, so afaict there are no immediate plans to drop support for older versions any time soon. However, this is something that we may look into for a future release *if it provides substantial value* :+1:

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this issue persists and we can reopen this :+1:

See also https://github.com/reactphp/react/issues/374
