### ISSUE TITLE
Allow Higher versions of Guzzle

### ISSUE THREAD

**Issue by WiR3D-kNiGhT** [reactphp/http#20]
with v3.9.2 out there are issues creeping up since react relies on the `3.0.*` `parser` and `http` from guzzle.

In my case I was just messing around with `BowerPHP`.

**Comment by cboden** [comment]
Any specific errors you are receiving?

**Comment by WiR3D-kNiGhT** [comment]
None specifically, and even if I did the odds are it will be BowerPHP, but
composer won't let me install guzzle since the required versions are
incompatible.

**Comment by cboden** [comment]
The biggest block right now is that Guzzle has change their API after version 3.

**Comment by WiR3D-kNiGhT** [comment]
Yeah. Unfortunately that won't go away going forward.
Is there missing functionally or is the problem that it will affect how devs use react?

**Comment by cboden** [comment]
Actually, it doesn't look like any Guzzle APIs are exposed through this React lib. If you'd like to open a PR using Guzzle 5 as the HTTP parser I'll take a look at it and merge it.

**Comment by WyriHaximus** [comment]
:+1: on that! The only thing that nags me is that Guzzle requires CURL on dev. Which most systems have installed so I'm wondering how that would affect out users @cboden?

**Comment by cboden** [comment]
`guzzle/guzzle` 3/4 requires `ext-curl`. `guzzlehttp/guzzle` 5 has `ext-curl` require-dev

**Comment by WyriHaximus** [comment]
That would work :+1: . Just checked the dependency tree and also RingPHP and Guzzle Streams at best require CURL as dev.
