### ISSUE TITLE
ErrorException in callbacks

### ISSUE THREAD

**Issue by ortreum** [reactphp/http#204]
Hi,

maybe I don't understand the concept of reactPHP not well enough. But if I use the functions

    error_reporting(0);
    set_error_handler([$this, 'handle'], E_ALL);
    set_exception_handler([$this, 'exception']);
    register_shutdown_function([$this, 'shutdown']);

I thought that they will work inside the callback too. Every typo returns a HTTP 500 in the exmple react/http. It would be much more easier if there would be an ErrorException for E_ERROR, E_WARNING ect. like

    function handle($code, $text, $file, $line)
    {
         throw new \ErrorException($text, $code, 1, $file, $line);
     }

This line from the README.md only works for Exceptions and not for E_FATAL or missing ; or E_WARNING:

    $server->on('error', function (Exception $e) {
        echo 'Error: ' . $e->getMessage() . PHP_EOL;
    });

But I want exceptions, something catchable. "Error 500" does not help me finding errors.
How can I do that myself?

Michael

**Comment by kelunik** [comment]
```php
$server->on('error', function (Exception $e) {
    echo 'Error: ' . $e->getMessage() . PHP_EOL;
});
```
should be
```
$server->on('error', function (Throwable $e) {
    echo 'Error: ' . $e->getMessage() . PHP_EOL;
});
```

**Comment by ortreum** [comment]
YASSS! That solves my problem and I have this beautiful test error stack trace:

    ParseError: syntax error, unexpected '__construct' (T_STRING), expecting function (T_FUNCTION) in D:\Webserver\reactPHP\server\test.php:5
    Stack trace:
    #0 D:\Webserver\reactPHP\vendor\react\http\src\Server.php(233): {closure)
       (Object(React\Http\ServerRequest))
    #1 ...
    #19 {main}

Thank you :D
