### ISSUE TITLE
Error when header parsing

### ISSUE THREAD

**Issue by gilberg-vrn** [reactphp/http#207]
When request target is origin-form and contain right absolute path, like this:
`GET /somepath?param=http://example.com HTTP/1.1`

`RequestHeaderParser` throw `InvalidArgumentException('Invalid absolute-form request-target')`

This error can be corrected by changing the test condition, for example
```
((!isset($parts['scheme'], $parts['host']) || $parts['scheme'] !== 'http' || isset($parts['fragment'])) && !isset($parts['path']))
```

**Comment by kelunik** [comment]
Your request isn't a valid URI.
