### ISSUE TITLE
Additional Body parsers

### ISSUE THREAD

**Issue by geggleto** [reactphp/http#225]
Related to #220 

In Slim we have quite a few different media parsers we include in our PSR-7 implementation however these limits are infrequently extended by some in specific industries. It would be super helpful to have the ability

1.  Have more than one media parser middleware as it's not always just 1 type of request body in a project

2. Have the ability to add more parsers to the middleware.

Here's our current strategy.

https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Request.php#L204-L241

**Comment by WyriHaximus** [comment]
https://github.com/WyriHaximus/reactphp-http-middleware-custom-request-body-parsers :sunglasses:

**Comment by geggleto** [comment]
@WyriHaximus ;)
