### ISSUE TITLE
Rename `Server` to `StreamingServer` and add new `Server` facade with sane defaults

### ISSUE THREAD

**Issue by clue** [reactphp/http#259]
Most clients should not have to care about concepts such as "streaming", "buffering" and "parsing". In particular, most of our examples completely ignore this fact. As such, it makes more sense to add a new `Server` that takes care of all this for the 80% use case. We will likely rename our current `Server` implementation to something like `StreamingServer` and implement a simple facade that uses our `RequestBodyBufferMiddleware` and `RequestBodyParserMiddleware`.

Refs #197 and #198

**Comment by WyriHaximus** [comment]
#260 is up, but a work in progress
