### ISSUE TITLE
Consider removing `Expect: 100-continue` request header

### ISSUE THREAD

**Issue by andig** [reactphp/http#262]
When we send 100 continue in https://github.com/reactphp/http/blob/master/src/Server.php#L225 shouldn‘t that header line be removed, similar to updating content length when buffering? Noticed this during building http proxy for php-pm.

**Comment by WyriHaximus** [comment]
Can't find anything in the specs about having to remove it. Did you run into issues with it?

**Comment by andig** [comment]
If I use the server to receive the request on proxy and slave side it will send the 100 twice which doesn‘t make sense?

**Comment by WyriHaximus** [comment]
Good point, does makes sense to remove it then I suppose. What do you think @clue ?

**Comment by clue** [comment]
I think you're raising a very valid point here! :+1: I would like to see what kind of implications this has, does anybody feel like filing a PR?

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I have no plans to change this myself anytime soon. Please come back if you feel this is still an issue and we can reopen this :+1:
