### ISSUE TITLE
Why not parsing JSON by default?

### ISSUE THREAD

**Issue by leocavalcante** [reactphp/http#306]
Why isn't `RequestBodyParserMiddleware` handling such a super common format on the web/HTTP workspace?

I thought that as just lack of implementation, but I found this:
https://github.com/reactphp/http/blob/master/tests/Middleware/RequestBodyParserMiddlewareTest.php#L180

**Comment by WyriHaximus** [comment]
Hey @leocavalcante we're not parsing JSON by default because it isn't part of the HTTP spec. However you can use https://github.com/WyriHaximus/reactphp-http-middleware-custom-request-body-parsers to parse JSON and XML bodies.
