### ISSUE TITLE
Buffering (stream) Response from big file (or not). Really without react/filesystem component?

### ISSUE THREAD

**Issue by vasilevrv** [reactphp/http#309]
Hi, please, read https://github.com/php-pm/php-pm/pull/367

I understand that this is impossible by design. Right?

**Comment by WyriHaximus** [comment]
Currently in the process of upgrading `react/filesystem` to the latest `react/*` components. What are you trying to achieve here, do you have a gist with what you want to do?

**Comment by vasilevrv** [comment]
Gist - able to transfer large files through a buffer (for economy memory) to client. But, ReadableResourceStream doesn't work with libevent (epoll can not attach file descriptors by design), which we use in our project.

We looked aside the react /filesystem, but yes, it was confusing that he was using outdated components.

**Comment by vasilevrv** [comment]
ok, we'll wait when the component is ready, thanks!

**Comment by clue** [comment]
The filesystem is inherently blocking, so this is not really a limitation of PHP-PM, this project or even libevent. This is why libraries such EIO (and others) implement a thread pool to work around this by blocking their respective threads only.

This means that this project is perfectly capable of using any kind of stream (including filesystem streams), provided you're using a non-blocking API to access this stream.

For filesystem based access, this would be https://github.com/reactphp/filesystem. Note that this project is under active development and currently lacking behind with updating to latest ReactPHP components.

Once https://github.com/reactphp/filesystem/issues/21 is in, these stream would also be supported here and in other projects building on top of this. As such, I don't think there's anything else that needs to be done in this project right now.

I hope this helps :+1:

**Comment by vasilevrv** [comment]
Thanks, clue!
