### ISSUE TITLE
Question: why are my handlers being called twice?

### ISSUE THREAD

**Issue by naroga** [reactphp/http#31]
I have the following snippet, which is a class method:

    public function start(OutputInterface &$output)
    {
        $loop = Factory::create();
        $socket = new Server($loop);
        $http = new \React\Http\Server($socket);
        $http->on('request', [$this, 'manageRequest']);
        $socket->listen(3440);
        $loop->run();
    }

Now, my class has the 'manageRequest' method:

    public function manageRequest($request, $response)
    {
        echo "I'm managing a request!", PHP_EOL;
    }

When accessing `http://localhost:3440`, I get the correct message: `I'm managing a request!`.

However, if I decide to respond to the browser request with a message, I get the `I'm managing a request!` message **twice**:

    public function manageRequest($request, $response)
    {
        echo "I'm managing a request!", PHP_EOL;
        $response->writeHead(200, ['Content-type' => 'text/plain']);
        $response->end('My response');
    }

One page hit prints the message twice:

    I'm managing a request!
    I'm managing a request!

How do I make my webserver respond only once?

**Comment by naroga** [comment]
Ok, I just figured out what was happening by dumping the `$request` variable. When accessing `http://localhost:3440`, my browser was also calling `http://localhost:3440/favicon.ico`, which was indeed two requests.

I apologize for the dumb question.

**Comment by AndreasHeiberg** [comment]
👍  thanks for sharing. Was thinking the same thing :)
