### ISSUE TITLE
Errors with Apache Bench

### ISSUE THREAD

**Issue by kelunik** [reactphp/http#311]
When I run `ab` to benchmark `examples/01-hello-world.php`, I get a few connection errors with `ab -n 10000 -c 100 http://127.0.0.1:44699/`

``` 
This is ApacheBench, Version 2.3 <$Revision: 1796539 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
apr_socket_recv: Connection reset by peer (104)
Total of 9958 requests completed
```

**Comment by WyriHaximus** [comment]
Could you provide more information about which loop you're using, what OS, and which version of this package?

P.S. Please leave the plugging of your own packages out of your issues, it isn't appropriate and appreciated. I've removed it from your post.

**Comment by kelunik** [comment]
Default stream select loop, PHP 7.2.0, latest `master` with latest dependencies.

Seems like the `apr_socket_recv` only happens with `xdebug` being enabled. Without `xdebug` I get one or multiple very slow requests.

```
Percentage of the requests served within a certain time (ms)
  50%      9
  66%      9
  75%     10
  80%     10
  90%     11
  95%     13
  98%     15
  99%     18
 100%   4339 (longest request)
```

**Comment by kelunik** [comment]
@WyriHaximus I've added it, because we've seen issues with `ab` exactly like that before, but it no longer happens there. I have no idea about the case though.

**Comment by clue** [comment]
This is more a limitation of how your TCP/IP stack and/or `ab` operates. For instance, this can easily be reproduced by running this against the latest `nginx` version.

You can check your netstat output and you'll find that you'll have plenty of `TIME_WAIT` connections listed. Once this number goes down again after a minute or two, this temporary error also goes away.

To reiterate: I'm not aware of any issues in production setups. This is only an issue if you open *thousands* of requests within very short time frames from the same source IP.

I'm not sure there's much that can be done here, so I'll close this for now. If you feel this was closed prematurely, please let us know and I'm happy to reconsider this :+1:

**Comment by kelunik** [comment]
@clue There are indeed quite some connections in the `TIME_WAIT` state, but these don't cause the connection errors. The connection errors only happen with xdebug enabled. Without xdebug, I get these results:

```
Percentage of the requests served within a certain time (ms)
  50%      8
  66%      8
  75%      8
  80%      8
  90%      9
  95%     11
  98%     13
  99%     51
 100%   4338 (longest request)
```

A small portion of requests take really long to be served. With xdebug it's significantly slower. I guess these slow requests are just too slow then, e.g. it might take to long to even accept these connections and that's why they error.

I get such long requests neither with our server nor Apache2 with the same command.

**Comment by clue** [comment]
@kelunik I can confirm that this issue is more apparent with `xdebug` enabled on my local machine. However I can also reproduce this with `xdebug` disabled or when using pretty much any HTTP server (including Apache and nginx) when using significantly larger numbers.

I haven't had a chance to look into this in more detail, but if you happen to have an idea what causes these differences and possibly what can be done to improve this, I'm more than happy to give it a try.

Until then, I'm not sure there's much that can be done here? :+1: 

For instance, this projects currently doesn't apply an particular socket options (except for `O_NONBLOCK`). Just a brain dump, but I can only assume that the other projects may apply custom options for `backlog`, `TCP_NODELAY`, `SO_LINGER` and others?

**Comment by kelunik** [comment]
We make use of the `backlog` option, but that doesn't really explain longer requests, I think. ~~My guess would be that we have immediate reads and writes where possible without going through an I/O watcher while ReactPHP doesn't do this.~~ Actually, it seems we only do immediate writes in the server, the immediate reads are only implemented in the byte-stream package, which the server doesn't make use of.

@trowski, do you have any idea what caused these long requests to disappear for us?

**Comment by clue** [comment]
@kelunik I can confirm that passing an explicit `backlog` parameter significantly improves this as expected. I'm testing this against the first example:

```php
$socket = new \React\Socket\Server('0.0.0.0:8080', $loop, array('backlog' => 128));
```

```
$ docker run -it --rm --net=host jordi/ab ab -n 10000 -c 100 http://127.0.0.1:8080/
```

Accordingly, using significantly larger numbers here makes this issue appear again :+1:
