### ISSUE TITLE
Segfault when running script

### ISSUE THREAD

**Issue by JamesMcAvoy** [reactphp/http#312]
I have a segfault when I run the script
I tried to increase memory limit to the script but it does not work

calling memory_get_usage and get_peak_usage :
```PHP
<?php

use ReactRouter\ReactRouter as Router,
	React\EventLoop\Factory,
	React\Http\Server,
	React\Http\Response,
	React\Socket\Server as SocketServer,
	Psr\Http\Message\ServerRequestInterface,
	Psr\Http\Message\ResponseInterface;

require __DIR__.'/vendor/autoload.php';

echo memory_get_usage()."\n";
echo memory_get_peak_usage()."\n";

$app = new Router();

$loop = Factory::create();

$server = new Server(function(ServerRequestInterface $request) use(&$app)  {

	$response = new Response(
		200,
		array(
			'Content-Type' => 'text/html',
			'X-Powered-By' => 'PHP '.phpversion()
		),
		'<html>body</html>'
	);

	return $response; //$app->run($request, $response);

});

$socket = new SocketServer(8080, $loop);
$server->listen($socket);

$loop->run();
```
it returns : (:fr:)
```
616424
743008
Erreur de segmentation
```

when i remove my router the error no longer appears (but I never had this error before running my router with an http php server)

Could the segfault be caused by the libevent ?
How to increase memory to the script ?
Is this kind of http php server using too much memory ?

**Comment by WyriHaximus** [comment]
Hey @JamesMcAvoy could you gist your `composer.json`? Would like to try this locally and see if I can reproduce it. Also which versions of PHP and libevent are you running?

**Comment by clue** [comment]
`ExtLibeventLoop` is not supported on PHP7, see also:

> This event loop does only work with PHP 5. An unofficial update for PHP 7 does exist, but it is known to cause regular crashes due to SEGFAULTs. To reiterate: Using this event loop on PHP 7 is not recommended. Accordingly, the Factory will not try to use this event loop on PHP 7.

https://github.com/reactphp/event-loop#extlibeventloop

You should use any of the other event loops, for example `ext-event` :+1:

**Comment by JamesMcAvoy** [comment]
Thanks, i read somewhere that a library was not supported on PHP7 but I was not sur

**Comment by WyriHaximus** [comment]
To clarify `react/http` supports PHP7, just the specific `ExtLibeventLoop` not.

**Comment by JamesMcAvoy** [comment]
Hello, just found my bug.

I had this method : 
```PHP
	public function setParam(String $key, $value) {
		if($key == '400' || $key == '404' || $key == '405') {
			if(!is_callable($value))
				throw new RouterException('Closure or callback function needed in second parameter in order to implement an HTTP error.');

			$this->httpErrors[$key] = $value;
		} elseif($key == 'BASE_URL' && is_string($value)) {
			if($value['0'] != '/')
				$value = '/'.$value;
			$this->params[$key] = $value;
		} elseif($key == 'CASE_SENSITIVE' && is_bool($value)) {
			$this->params[$key] = $value;
		} else throw new RouterException('BASE_URL or CASE_SENSITIVE keys are needed with string or bool in second parameter');

		return $this;
	}
```

As you can see there is an infinite loop. The problem did not come from ExtLibeventLoop (I installed ext-end, it works, thanks).

I want to kill me, this is a beginner mistake.

**Comment by clue** [comment]
No worries, happy to hear you've got this resolved one way or another :grinning:
