### ISSUE TITLE
About psr7

### ISSUE THREAD

**Issue by mirabilos** [reactphp/http#319]
Hi,

your `composer.json` has a reference to [`ringcentral/psr7`](https://github.com/ringcentral/psr7) which is a fork of [`guzzlehttp/psr7`](https://github.com/guzzle/psr7), which is quite behind, but does have seven new commits (some of which _appear_ to also be in guzzle).

While packaging Movim, I notice that all other dependencies that require an psr7 use guzzle already; do you think react-http will also work with it, and if so, can we change that in the composer file?

**Comment by mirabilos** [comment]
Jan Sorgalla dixit:

>`ringcentral/psr7` i used because `guzzlehttp/psr7` is PHP >=5.4 while
>`react/http` (and `ringcentral/psr7`) are PHP >= 5.3.

OK, thanks, so we can just replace it since we have PHP 7.2 anyway.

**Comment by quazardous** [comment]
I've got

```
User Deprecated: Method "Psr\Http\Message\StreamInterface::getMetadata()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "RingCentral\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
```

Cannot create issue in `ringcentral/psr7`, so I put it there for now.

**Comment by clue** [comment]
@quazardous This seems unrelated, may I ask you to file a separate ticket to discuss this in more detail? In particular, make sure to list what steps you did perform to raise this error.

**Comment by quazardous** [comment]
The relation is the state of maintenance of `ringcentral/psr7`. I'll create a new issue.
