### ISSUE TITLE
Limits of 'Server' fascade should be documented in readme

### ISSUE THREAD

**Issue by gopi-ar** [reactphp/http#326]
Spent quite a bit of time figuring out why my reverse proxy was synchronous; tried multiple http clients, promises and events, etc. Finally discovered my `post_max_size` is nearly equal to `ini_get_limit` and `Server` has built-in throttling logic. We use higher post_max_size on dev systems for easier imports into phpmyadmin, etc.

This should be better documented in the docs..

**Comment by WyriHaximus** [comment]
How would you propose we'd improve our documentation? To me the section on this https://reactphp.org/http/#server is pretty clear. But we're always open for PR's improving out documentation

**Comment by woytam** [comment]
I agree and prepared a small PR #335. But I think, it is a good idea to add this info again to section `Server`.

**Comment by woytam** [comment]
I have created one more PR #336 with explicit warning about setting `memory_limit` and `post_max_size` on development machines.

**Comment by clue** [comment]
@gopi-ar Thank you for bringing this to our attention, I agree that it makes sense to add some documentation for this! :+1: 

I've just filed #342 to add some additional documentation for the concurrency limit and how to possibly avoid hitting this limit. Let me know what you think about this :+1:
