### ISSUE TITLE
StreamingServer defeats StreamInterface

### ISSUE THREAD

**Issue by phpbg** [reactphp/http#328]
`StreamInterface` is defeated :
* By assigning strings to `$body`
* By casting `$body` to string when writing it to connection

`$body` should remain a `StreamInterface` and should be send by chunks to avoid loading all its content to memory (unnecessary allocation of memory in case of big bodies).

```php
            // response to HEAD and 1xx, 204 and 304 responses MUST NOT include a body
            $body = '';
```
```php
            if ($body instanceof ReadableStreamInterface && $chunked) {
                $body = "0\r\n\r\n";
            }
```

```php
            // end connection after writing response headers and body
            $connection->write($headers . "\r\n" . $body);
```

**Comment by clue** [comment]
@phpbg Thanks for reporting, I understand where you're coming from!

This project being an event-driven, non-blocking implementation and PSR-7 being a definition for synchronous environment means we've had to implement a number of work-arounds that result in some known limitations. In your case, it sounds like you want to stream a response body which requires a `ReadableStreamInterface`. For more details, this should be covered in the documentation: https://github.com/reactphp/http#streaming-response

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by clue** [comment]
> This is not exactly about blocking or non-blocking.
> This is more about memory.
> At the beginning I simply thought of something like :
> 
> ```
> if ($body instanceof StreamInterface) {
>                 $chunkSize = 65535;
>                 while (! $body->eof()) {
>                     $chunk = $body->read($chunkSize);
>                     $connection->write($chunk);
>                 }
>             }
> ```

This is pretty much what ReactPHP is all about: efficient I/O :-)

PSR-7 defines a number of synchronous interfaces (which makes perfect sense tbqh) and as such assumes control over I/O. That very `read()` method assumes that *you* are in control of managing I/O, while ReactPHP works under the assumption that an *event* will be fired once I/O is ready.

If you want to have filesystem access, you may want to take a look at https://github.com/reactphp/filesystem. Other than that, there are also a number of stream implementations for all kinds of network protocols: https://github.com/reactphp/stream#creating-streams

I understand that it may be frustrating we can't provide full compatibility in this instance, but at the same time it's my understanding that providing these alternatives would fulfill most of the use cases. I hope this helps for your particular use case :+1:
