### ISSUE TITLE
Replace advanced StreamingServer with StreamingRequestMiddleware

### ISSUE THREAD

**Issue by clue** [reactphp/http#343]
The advanced `StreamingServer` can be used for [streaming requests](https://github.com/reactphp/http#streaming-request). This is not to be confused with with [streaming responses](https://github.com/reactphp/http#streaming-response) and the higher-level [Server](#server) class.

The current situation has caused some confusion as to which server implementation to use and when a "streaming" server is really needed. Right now, the `StreamingServer` is quite low-level and is used internally in the `Server`.

As an alternative, I would like to mark the `StreamingServer` internal only (BC break) and instead propose using a (yet to be built) `StreamingRequestMiddleware`. This way, the user has to make an explicit choice in their request handler chain *where* the request should be streaming. In order to preserve BC behavior for most common use cases, it would automatically buffer the request in the middleware stack.

**Comment by WyriHaximus** [comment]
Not sure if I'm into this idea, I like the separation between the two. Also how would we inject the `StreamingRequestMiddleware` before the current buffering middleware and also inject the rest of our middleware after it?

**Comment by mbonneau** [comment]
Would this change how things like `WebSocketMiddleware` work with `react/http`?

**Comment by clue** [comment]
@WyriHaximus Specific implementation details may vary, but here's how this could potentially look from a consumer's perspective:

```php
$server = new React\Http\Server([
    new StreamingRequestMiddleware(),
    new MyRequestHandler()
]);
```

This means that users will have to make an explicit choice to use streaming requests. This implies that we will likely have to check the request handler chain to see which middleware handlers are included and adjust this list accordingly. In other words: If the chain does not specifically mention "streaming", we should use a buffered request by default.

@mbonneau I don't think this should have any effect on HTTP upgrade requests. The initial HTTP request does not usually contain a request body, so this should not affect whether you're using a streaming or a buffered request. I agree that this sounds confusing and this is something that should be improved in our documentation. I would argue that the current state is perhaps even more confusing, because `StreamingServer` seems to imply the wrong thing here: It is specifically not required for streaming response bodies or HTTP upgrade requests.

**Comment by WyriHaximus** [comment]
@clue the specific implementation details is what I'm interested in. Do like this idea but not sure yet how this would work internally since `Server` is inherently buffering
