### ISSUE TITLE
Actually "unstable"?

### ISSUE THREAD

**Issue by andyfleming** [reactphp/http#35]
I noticed the repo description says "unstable". I'm not very familiar with the project. Is that still accurate?

**Comment by voidcontext** [comment]
The better question is: is this project still alive?

**Comment by WyriHaximus** [comment]
The project is still active and worked on. One of the reasons it is still
unstable is because it's lacking full HTTP 1.1 support, we're working on
that. As far as stability goes for the HTTP parts we've implemented, they
are stable.

**Comment by ephrin** [comment]
@WyriHaximus bw, where I can find the latest version fork? Or some red tests to implement? Wanna help with.
Currently experimenting with threaded app. So need normal PHP http stream server ;)
Todos at [react#3](https://github.com/reactphp/react/issues/3) are still actual ones? Gimme the bone!)

**Comment by WyriHaximus** [comment]
@ephrin cool! Lets see what about gzip encoding, should be fairly easy to get started? (The equivalent PR on `react/http-client`: https://github.com/reactphp/http-client/pull/50.) I'll create issues for them when I get home. And yes to answer your question the TODO on #3 is still relevant.

**Comment by ephrin** [comment]
@WyriHaximus I don't think gzip encoding is the necessary feature for a server. But can try if it's a good point to start :ok_hand:

**Comment by WyriHaximus** [comment]
@ephrin fair point but gzip encoding to send a gzipped result back to the client could be interesting

**Comment by ephrin** [comment]
🏭

**Comment by clue** [comment]
Thanks for filing this ticket, I can assure you we're working hard on this :+1: This repo is under active development and has received quite a few updates in the last weeks, so it's anything but dead :)

We've filed ticket for all known issues and missing features and filed new milestones for the upcoming releases to keep track of this. This means that we'll likely remove the "unstable" comment soon once the major blockers have been resolved here :+1: 

I believe this has been answered, so I'll close this for now. If this problem persists, please come back with more details and we can reopen this :+1:
