### ISSUE TITLE
Changelog entry for 0.8.6 release

### ISSUE THREAD

**Issue by gdejong** [reactphp/http#358]
I noticed that `v0.8.6` was released last month, but the current changelog does not mention it.

Could you maybe update the changelog with this new version?

Thanks!

**Comment by WyriHaximus** [comment]
My bad, will update it later today

**Comment by WyriHaximus** [comment]
And I kept forgetting, just pushed https://github.com/reactphp/http/commit/390ca707ecdf097a0039b99bff2210a204ef7063 with the updated changelog
