### ISSUE TITLE
Remove X-Powered-By: React/alpha or make optional

### ISSUE THREAD

**Issue by andyfleming** [reactphp/http#36]
For security reasons, among others, we should remove the `X-Powered-By` header.

**Comment by WyriHaximus** [comment]
I'm in favor of this by passing an option array to the `Server` which passes a default headers array into the `Response` constructor. Any opinions on this @jsor @clue @cboden?

**Comment by clue** [comment]
I agree that we should add an option to turn this off (though I'm not considering this to be *security* feature) :+1:

**Comment by jsor** [comment]
:+1:

**Comment by clue** [comment]
I stumbled upon this while preparing a fix for #51.

You can actually omit sending the `X-Powered-By` header by explicitly setting an empty header value like this:

```php
$response->writeHead(200, array('X-Powered-By' => array()));
```

I believe this should answer this ticket, but I'll leave this open until I've filed my upcoming PR that adds some documentation for this :+1:

**Comment by andyfleming** [comment]
It's a form of information disclosure and should be off by default.

**Comment by clue** [comment]
This is now documented behavior via #107, do you feel this needs to changes further?

FWIW, PHP also exposes a similar header by default, unless otherwise configured: http://php.net/manual/en/ini.core.php#ini.expose-php

**Comment by WyriHaximus** [comment]
@clue tbh I agree with @andyfleming here, we're disclosing information we probably shouldn't from a security perspective. I know PHP, Nginx, Apache, Varnish etc etc all expose that but I won't consider that a good security practice. And while we're making breaking changes for `0.5.0` and `0.6.0` I wouldn't mind fixing this.

**Comment by andyfleming** [comment]
Most (if not all) of those have options to turn off the powered by header. It's a recommended best practice to not expose the service and version. It's to avoid revealing that a server is running an vulnerable (unpatched) version of a service.

**Comment by clue** [comment]
> Most (if not all) of those have options to turn off the powered by header.

So does this component?

I'm really not saying I disagree here, but what do you suggest? Can you file a PR that addresses the issue you're seeing? Thanks!

@WyriHaximus Sounds like a reasonable plan! I suppose we'll likely have to resolve this once #28 lands anyway, because creating the response object will likely be left up to the user anyway, so there's little chance for us to add any "default headers".

**Comment by andyfleming** [comment]
I'm not seeing any issue, per se, just suggesting we be [Secure by Default](https://en.wikipedia.org/wiki/Secure_by_default).

It's not a big deal at all. Just advocating for best practices.

**Comment by WyriHaximus** [comment]
@clue agreed, all they have to do is return a response anyway after #28 landed. No need for us to provide that anymore :smile:

**Comment by ethernidee** [comment]
Any unhandled exception will still result in error 500 + revealed X-Powered-By. It must be secure by default without crutches.

**Comment by ethernidee** [comment]
Unhandled exception may still result in error 500 + revealed X-Powered-By. It must be secure by default without crutches.

**Comment by WyriHaximus** [comment]
@ethernidee I'm open for a PR that respects the `expose_php` ini setting like we done at several other places
