### ISSUE TITLE
Division by zero in src/Server.php line 175

### ISSUE THREAD

**Issue by smscr** [reactphp/http#360]
https://github.com/reactphp/http/blob/248202e57195d06a4375f6d2f5c5b9ff9da3ea9e/src/Server.php#L175

The problem is, in Server.php at line 175 it is assumed that ```post_max_size``` will always be a set limit.

However, according to PHP manual: 
```Allow unlimited post size by setting post_max_size to 0.```
https://www.php.net/manual/en/ini.core.php#ini.post-max-size

reactphp/http v0.8.6
PHP 7.1.33

**Comment by clue** [comment]
@smscr Thanks for reporting, I can indeed reproduce this with `post_max_size=0`. Does anybody feel like filing a PR to address this? :+1: 

In the meantime, you can work around this by setting `post_max_size` to a large value, this should have the same effect.

**Comment by smscr** [comment]
@clue I've thought about a fix, and I see there is an intention to calculate an amount of request that can be handled concurrently, based on the memory limit and post_max_size.

I'm not sure what amount of request we should estimate to be possible the the post_max_size is unlimited, so that is why I'm not suggesting a PR to address this.

There could be several approaches.
- To ignore the estimation and return self::MAXIMUM_CONCURRENT_REQUESTS? But what if the concurrent requests will exceed the memory then?
- To limit to one concurrent request? But wouldn't that decrease the performance?
- To change the estimation formula to use something other than post_max_size, but what in particular?
