### ISSUE TITLE
Session usage

### ISSUE THREAD

**Issue by BenjaminLeibinger** [reactphp/http#383]
Hello, 

i am trying to use sessions. As an example i use the Cookie example and extend it for sessions.

```php
<?php

use Psr\Http\Message\ServerRequestInterface;
use React\EventLoop\Factory;
use React\Http\Message\Response;
use React\Http\Server;

require __DIR__.'/../vendor/autoload.php';

$loop = Factory::create();

$sessionTimeout = 10800;
$le = PHP_EOL.'</br>';

$server = new Server($loop, function (ServerRequestInterface $request) use ($sessionTimeout, $le) {
    $key = 'PHPSESSID';
    session_start();
    $id = session_id();

    ob_start();
    echo "generated id: $id $le";

    if (isset($request->getCookieParams()[$key])) {
        echo "Your cookie value is: ".$request->getCookieParams()[$key].$le;
    }

    if (empty($_SESSION['count'])) {
        $_SESSION['count'] = 1;
    } else {
        $_SESSION['count']++;
    }

    echo "Session counter: ".$_SESSION['count'].$le;

    $expires = gmdate('D, d-M-Y H:i:s', time()+$sessionTimeout);
    $cookieString = sprintf('%s=%s; Expires=%s; Max-Age=%s; Path=/; HttpOnly', $key, $id, $expires, $sessionTimeout);

    if (PHP_SESSION_ACTIVE === session_status()) {
        echo "write close... $le";
        session_write_close();
    }

    // reset session_id in any case to something not valid, for next request
    session_id('');
    session_unset();
    //unset($_SESSION);

    $out = @ob_get_clean();

    $body = '<!DOCTYPE html>
<html>
<body>
'.$out.'</body>
</html>
';

    return new Response(
        200,
        [
            'Content-Type' => 'text/html',
            'Set-Cookie' => $cookieString,
        ],
        $body
    );
});

$socket = new \React\Socket\Server(isset($argv[1]) ? $argv[1] : '0.0.0.0:0', $loop);
$server->listen($socket);

$loop->run();

```

Starting the script with: ```php sessiontest.php 127.0.0.1:8002```

Without the ```session_id('') ``` every request and every user gets the same session id. With the ```session_id('') ``` enabled every request gets a new id even if the session cookie is set. 

Currently i am not shure which part is the problem. Do i understand the sessions wrong? Is this problem dependent to php cli or to the react approach?

Maybe somebody has a hint for me.

**Comment by clue** [comment]
@BenjaminLeibinger Thanks for reporting, this is an interesting one!

It looks like you *can* indeed make PHP's session handler work with this async request handler. It looks like you're pretty close already, but you would also have to pass the session identifier from the incoming request cookie to `session_id()`.

The real question becomes whether one *should* make it work with this project. PHP's session handling is designed for PHP's traditional fire-and-forget request handling and works by exposing global state. Additionally, it uses a filesystem-based session mechanism by default. This together makes it a poor fit for an execution environment that supports concurrent requests.

As an alternative, I would suggest going for a session handler that relies on processing the request/response by implementing a middleware handler. This way, you can expose a session object to the incoming request object and you don't have to rely on global state.

For example, it looks like https://github.com/jasny/session-middleware could be a good starting point. I don't think an async-aware session handler works at the moment, but this would definitely be an interesting endeavor :muscle: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
