### ISSUE TITLE
Forwarding requests to multiple ports as json.  Second one arrives empty.

### ISSUE THREAD

**Issue by eitelkrauss** [reactphp/http#387]
Trying to forward requests to multiple ports as application/json, but the second request arrives empty.  This doesn't happen when sent as text/plain.

```

<?php

require_once 'vendor/autoload.php';

$loop = \React\EventLoop\Factory::create();

$browser = new \React\Http\Browser($loop);

$clients = ["http://127.0.0.1:8001", "http://127.0.0.1:8002"];

$server = new \React\Http\Server($loop, function (\Psr\Http\Message\ServerRequestInterface $request) use ($browser, $clients){
    
    # forward requests to multiple ports as json
    foreach($clients as $client){
        $browser->post(
            $client,
            ['Content-Type' => 'application/json'],
            $request->getBody()
        )
    }
    # this works and is received on both 8001, 8002
    foreach($clients as $client){
        $browser->post(
            $client,
            ['Content-Type' => 'text/plain'],
            "hello"
        )
    }
});

$socket = new \React\Socket\Server('127.0.0.1:8000', $loop);

$server->listen($socket);

$loop->run();
```

**Comment by legionth** [comment]
The request uses a `RingCentral\Psr7\BufferStream` as return value of `$request->getBody()`. By calling `$request->getBody()` this buffer will be emptied and is not available for our future requests. 

What you may want is to call `$request->getBody()->getContents()` and save the value to a variable for reusage.

I hope this helps 👍

**Comment by eitelkrauss** [comment]
@legionth works! thank you!! :)

**Comment by clue** [comment]
@eitelkrauss Thanks for bringing this up!

I agree that only being able to read the request body once (and only for some requests) is somewhat inconsistent, so I've just filed #395 to make sure you can always read the raw request body. Note that the `getContents()` method will only read the remainder of the buffer as per the PSR-7 definition. Reading will advance this previous position, so a second call will return an empty string unless you `rewind()` or `seek()` the request body.

In your specific use case, assigning this to a string once and reusing this sounds like a reasonable alternative :+1:
