### ISSUE TITLE
Original body removed when parsedBody is provided

### ISSUE THREAD

**Issue by mcustiel** [reactphp/http#390]
Hello.
I noticed this behavior:
I send this request to ReactPHP: 
`curl -X POST -H "Content-Type: application/json"  -d '{"param1":"value1","param2":"value2"}' http://localhost:8086/test`
Because application/json body is not parsed, I can access the raw body through `$request->getBody()` without any problem. If I call `$request->getParsedBody()` it will return null.
Then I send this request, were the content type is `application/x-www-form-urlencoded`:
`curl --data "param1=value1&param2=value2" http://localhost:8086/test`
The body will be parsed and I can access the variables through `$request->getParsedBody()`, but if I try to access the raw body I can't do it. 
My application (https://github.com/mcustiel/phiremock) relies on having access to the raw body to validate configurations provided by the client, could you please accept to access the raw request body even though it's parseable?

**Comment by WyriHaximus** [comment]
Hey @mcustiel we only included support for direct HTTP related body types. Have a look at https://github.com/WyriHaximus/reactphp-http-middleware-custom-request-body-parsers for JSON parsing

**Comment by mcustiel** [comment]
Hello @WyriHaximus  
I see now that my explanation was a bit confusing.
My issue is as following:
If I send a request with an unparseable body (json or plain text), I can access it on the server side using `$request->getBody()`. That's correct.
But if I send a request with a parseable body (for instance with `Content-Type: application/x-www-form-urlencoded`) then I can't access the raw request body through `$request->getBody()`, it will be an empty string. I can only access it through the `getParsedBody` method.

**Comment by WyriHaximus** [comment]
@mcustiel Ah ok I get it now.

Hey @clue what do you think about a marker middleware like `StreamingRequestMiddleware` but that one for not parsing the raw request body? (Note @mcustiel that this would mean no parsing for everything, if you still want to parse certain routes, have a look at https://github.com/WyriHaximus/reactphp-http-contextual-middleware-runner .)

**Comment by clue** [comment]
@mcustiel Thanks for bringing this up!

I agree that clearing the request body for *some* requests is somewhat inconsistent, so I've just filed #395 to make sure you can always read the raw request body.

**Comment by clue** [comment]
Closed via #395 :shipit:

**Comment by mcustiel** [comment]
Thank you for fixing this.
