### ISSUE TITLE
How can you turn off ssl verification?

### ISSUE THREAD

**Issue by crwh05** [reactphp/http#394]
I need to make parallel requests to a site that cannot have SSL certs as the DNS endpoint changes periodically.

I found I can use the blocking call [Clue\React\Block\awaitAll()](https://github.com/clue/reactphp-block#awaitall) to achieve this within our synchronous framework. 

It works with the [React\Http\Browser::post()](https://github.com/reactphp/http#post) function but I cannot turn off SSL verification in the post function.

[React\HttpClient\Client](https://github.com/reactphp/http-client) allows you to define a Connector which lets you set the [TLS context options](https://github.com/reactphp/socket#connector) `verify_peer` and `verify_peer_name` to false. I can make the request to the endpoint successfully with this method but I cannot use the client and connector in the blocking call as they return a React\HttpClient\Request object not a promise so I can't use the `awaitAll()` function.

Can the TLS functionality be added to the `Browser::post()` function as an option or is there a way to use the Clue `awaitAll()` function with the HtpClient function?

**Comment by crwh05** [comment]
Here is a working example of a simple HttpClient request that successfully returns a result with HTTP 200:
```
$dns = 'https://ec2-*-*-*-*.eu-west-1.compute.amazonaws.com:8000';
$post_data = 'test=12345';
$loop = React\EventLoop\Factory::create();
$connector = new \React\Socket\Connector($loop, array(
    'tls' => array(
        'verify_peer' => false,
        'verify_peer_name' => false
    )
));
$client = new React\HttpClient\Client($loop, $connector);

$request = $client->request(
    'POST',
    $dns,
    [
        'Content-Length' => strlen($post_data),
        'Content-Type' => 'text/plain'
    ]
);
$request->end($post_data);

$request->on('response', function ($response) {
    $response->on('data', function ($chunk) {
        echo $chunk;
    });
});
$loop->run();
```


When I try the same using Http\Browser it doesn't work and I get a HTTP 500 error:

```
$dns = 'https://ec2-*-*-*-*.eu-west-1.compute.amazonaws.com:8000';
$loop = React\EventLoop\Factory::create();
$connector = new \React\Socket\Connector($loop, array(
    'tls' => array(
        'verify_peer' => false,
        'verify_peer_name' => false
    )
));
$client = new React\Http\Browser($loop, $connector);
$post_data = 'test=12345';

$client->post(
    $dns,
    [
        'Content-Length' => strlen($post_data),
        'Content-Type' => 'text/plain'
    ],
    json_encode($data)
)
    ->then(
        function (Psr\Http\Message\ResponseInterface $response) {
            var_dump((string)$response->getBody());
        }, 'printf');

$loop->run();
```

Can anyone explain why they get different results?

**Comment by clue** [comment]
@crwh05 Thanks for posting! It looks like you've got this right, you can configure the `Connector` to change TLS settings which will then be used by the `Browser`.

The `Client` is internal only, so I'll focus on the second example. I'm not sure if your second example is complete, but it looks like it's referencing an unknown `$data` variable (vs `$post_data`)? Additionally, the `Content-Length` header can be omitted as it will be set automatically.

The "HTTP 500 error" you're seeing means that TLS/HTTPS does work as expected, but the server returned an error for the request. Might be the above variable, but hard to tell without being able to access the same server.

The below example works just fine:

```php
<?php

require __DIR__ . '/../vendor/autoload.php';

$loop = React\EventLoop\Factory::create();
$connector = new React\Socket\Connector($loop, [
    'tls' => [
        'verify_peer' => false
    ]
]);
$client = new React\Http\Browser($loop, $connector);

$data = [
    'name' => 'Alice'
];

$client->request(
    'GET', // change to POST, but badssl.com only accepts GET
    'https://self-signed.badssl.com/',
    [
        'Content-Type' => 'application/json'
    ],
    json_encode($data)
)->then(function (Psr\Http\Message\ResponseInterface $response) {
    var_dump($response->getHeaders(), (string)$response->getBody());
}, 'printf');

$loop->run();
```

I hope this helps :+1:

**Comment by crwh05** [comment]
Hi @clue,

Thanks for your detailed response, especially for clarifying TLS/HTTPS does work as expected as I received an HTTP 500. That allowed me to focus on other points.

Regarding the use of `$post` and not `$post_data` there was a simple mistake while copying the sample code where I forgot to update the name of the post data being passed. (I had to change a few things as some info was sensitive)

That was not the issue but what was the issue was that while testing various endpoints (ones with SSL certs and ones without) I forgot to remove the `json_encode()` from the data passed in the post request when I was only sending `text/plain` instead of `application/json`.

The server was receiving the body as `"test=12345"` instead of `test=12345`
This was causing the issue.

**Comment by clue** [comment]
@crwh05 Thanks for the feedback!

Yeah, JSON-encoding a string is a nasty oversight, happy to hear my response has helped and you've got this working now! 💪
