### ISSUE TITLE
Returning Promise doesn't make Server any faster

### ISSUE THREAD

**Issue by mityukov** [reactphp/http#408]
Hi, can't fire out how to make server "parallel".

Here's the code:
```php
class ApiProxy extends Command
{
    public function handle()
    {
        $this->loop = \React\EventLoop\Factory::create();

        $server = new \React\Http\Server($this->loop, function (\Psr\Http\Message\ServerRequestInterface $request)
        {
            dump(microtime(true)); // <<< ATTENTION
        
            return new Promise(function ($resolve) use ($request) {
                $res = $this->doMakeRequest($request); // synchronous func returning \React\Http\Message\Response

                $resolve($res);
            });
        });

        $socket = new \React\Socket\Server(8080, $this->loop);
        $server->listen($socket);

        $this->loop->run();

        return 0;
    }

    public function doMakeRequest(\Psr\Http\Message\ServerRequestInterface $request)
    {
        sleep(1); // say we have something long

        return new \React\Http\Message\Response(
            200,
            [],
            'OK',
        );
    }
}
```

Now, in tinkerwell (Laravel tool for running arbitrary commands):
```php
Http::pool(fn ($pool) => [
    $pool->get('http://localhost:8080/blah/blah'),
    $pool->get('http://localhost:8080/blah/blah'),
    $pool->get('http://localhost:8080/blah/blah'),
    $pool->get('http://localhost:8080/blah/blah'),
]);
```
(I've tried `wrk` — same story…)

**Expectations:** that `dump(microtime(true));` will display very close values four times, and after approx 1 seconds all the responses will be served;

**Observed behavior:** no next requests starts before the previous one is served. Here's what I see in the console (where the server "dumps" to:
```
1623842903.6388
1623842904.6606
1623842905.6618
1623842906.6643
```

Can't figure out what's wrong…

**Why I think it SHOULD work differently:** this part of docs: 

> The example above returns the response directly, because it needs no time to be processed. Using a database, the file system or long calculations (in fact every action that will take >=1ms) to create your response, _will slow down the server. To prevent this you SHOULD use a ReactPHP Promise_. This example shows how such a long-term action could look like:

**Comment by d0niek** [comment]
`sleep()` function is blocking function so it block your event loop. I think you should use this one https://github.com/reactphp/event-loop#addtimer to emulate "something long"

**Comment by mityukov** [comment]
I just thought that "a real operation" would also be blocking (in my case, it would be a synchronous Laravel Http client performing request to another service). My question is: why doesn't the webserver take a new request immediately after returning a promise?

**Comment by WyriHaximus** [comment]
> `sleep()` function is blocking function so it blocks your event loop. I think you should use this one https://github.com/reactphp/event-loop#addtimer to emulate "something long"

Even better, use: https://reactphp.org/promise-timer/#resolve

> My question is: why doesn't the webserver take a new request immediately after returning a promise?

Assuming you are not doing anything blocking; it does.

**Comment by mityukov** [comment]
> Assuming you are not doing anything blocking; it does.

If I'm using GuzzleHttp inside `doMakeRequest` — will it be blocking?

**Comment by WyriHaximus** [comment]
> > Assuming you are not doing anything blocking; it does.
> 
> If I'm using GuzzleHttp inside `doMakeRequest` — will it be blocking?

Most likely yes, have a look at: https://reactphp.org/http/#client-usage

**Comment by clue** [comment]
The promise API helps making async code easier, a promise doesn't make anything "faster" by itself.

In your case, you want to use non-blocking primitives to avoid blocking the server and allow concurrent execution. As @WyriHaximus pointed out, instead of sleeping, you would want to use a timer that triggers any following logic at a later time. The promise API helps with making this more manageable than using primitive callbacks.

For more realistic use cases, you want to a non-blocking alternative to anything that could block your loop. See https://github.com/reactphp/reactphp/wiki/Users for a list of some common examples.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
