### ISSUE TITLE
HTTP Client: Redirect with 307 (Temporary Redirect) should keep original request method and body

### ISSUE THREAD

**Issue by olegbaturin** [reactphp/http#409]
As it stated at [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307)
_The method and the body of the original request are reused to perform the redirected request._

But [here](https://github.com/reactphp/http/blob/bc537273d11ee769c723a830e63aa33c0c35a530/src/Io/Transaction.php#L265) request is converted from POST to GET.

**Comment by clue** [comment]
@olegbaturin Thanks for reporting, I agree this is something that should be supported by this project :+1: 

PRs to address this very much welcome! :shipit:
