### ISSUE TITLE
Uncaught InvalidArgumentException: Invalid request handler given

### ISSUE THREAD

**Issue by lphwxl** [reactphp/http#415]
`
// 日志中间件
$loggingMiddleware = function(Psr\Http\Message\ServerRequestInterface $request, callable $next) {
    echo date('Y-m-d H:i:s') . ' ' . $request->getMethod() . ' ' . $request->getUri() . PHP_EOL;
    return $next($request);
};

$routeMiddleware = function (Psr\Http\Message\ServerRequestInterface $request) {
    return new React\Http\Message\Response(
        200,
        array(
            'Content-Type' => 'text/plain'
        ),
        "Hello World!\n"
    );
};

$server = new React\Http\Server([
    $loggingMiddleware,
    $routeMiddleware
]);
$socket = new React\Socket\Server('127.0.0.1:8080');
$server->listen($socket);
echo "Server running at http://127.0.0.1:8080" . PHP_EOL;
`
**【Error】**
  PHP Fatal error:  Uncaught InvalidArgumentException: Invalid request handler given in /xxx/vendor/react/http/src/Server.php:215

![image](https://user-images.githubusercontent.com/23658463/126751231-2cb1c731-7582-48da-9494-25f2d22521de.png)

【success】

![image](https://user-images.githubusercontent.com/23658463/126751490-ebb53dcc-f340-4df7-b725-f9b0a29c3efa.png)
或者
![image](https://user-images.githubusercontent.com/23658463/126751555-e329e578-d84c-4afb-b62e-3c35361ecbb5.png)

**Comment by WyriHaximus** [comment]
As of `1.0` the server no longer accepts an array of middleware/handlers but expects them to be passed in directly. If you change:

```php
$server = new React\Http\Server([
$loggingMiddleware,
$routeMiddleware
]);
```

To:

```php
$server = new React\Http\Server(
$loggingMiddleware,
$routeMiddleware
);
```

It will work
