### ISSUE TITLE
[http] pre-shutdown: how to refuse new connection while finishing on going stuff

### ISSUE THREAD

**Issue by quazardous** [reactphp/http#416]
hi,

I'm wondering how I can tell the server to stop listening and opening new connection but to finish ongoing request.

I want to gracefully stop/start each servers and let the loadbalancer know that this server is down (refuse new connection).

just calling `$loop->stop()` ?

**Comment by WyriHaximus** [comment]
Use the [`React\Socket\Server::close`](https://reactphp.org/socket/#close) method for that. That will make your application stop listening for any new connections but still handle any ongoing.

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:

(Also refs #396 for a similar use case.)
