### ISSUE TITLE
Testing the response

### ISSUE THREAD

**Issue by TLyngeJ** [reactphp/http#43]
I'm trying to write a unit test, in an application that uses https://packagist.org/packages/react/react, where I want to know if the Response objects has been written successfully. You know, header is set properly to return status 200, it contains some text that is going to be returned to the browser, maybe that isWriteable() is false and all of that.

What is the proper way of checking that?

**Comment by ephrin** [comment]
Have you seen [tests](/reactphp/http/tree/master/tests) files? There are some units that may help you with your own if I understand your question.

**Comment by clue** [comment]
I believe this has been answered :+1: 

I'll close this for now, please come back with more details if this problem persists and we can reopen this :+1:
