### ISSUE TITLE
Deprecation warning in ringcentral/psr7

### ISSUE THREAD

**Issue by quazardous** [reactphp/http#435]
I'm using the **http** server with a Synfony 5.4 bootstrap.

SF tracks deprecated stuff (I don't know exactly how).

I've this message

```
User Deprecated: Method "Psr\Http\Message\StreamInterface::getMetadata()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "RingCentral\Psr7\Stream" now to avoid errors or add an explicit @return annotation to suppress this message.
```

Issues can not be created in the forked repo so I open it there (cf #319).

my phpstan is also complaining about `ringcentral/psr7`

```
[phpstan] Method RingCentral\Psr7\Request::withHeader() should return static(RingCentral\Psr7\Request) but returns RingCentral\Psr7\Request.
[phpstan] PHPDoc tag @var has invalid value ($stream): Unexpected token "$stream", expected type at offset 45
```

It's only phpDoc stuff but in my version upgrade flow I try to eliminate all deprecation issue ASAP.

**Comment by SimonFrings** [comment]
@quazardous thanks for bringing this up 👍 

It seems like this problem isn't coming from the react/http component, a similar topic can be found here: ratchetphp/Ratchet#950.

We're only using a small part of RingCentral so the plan is to drop this in a future version. Additionally, we want to build our own implementation that adds some more functionality we can use (async implementations etc.).

If you have some ideas for an implementation until then, feel free to open up a pull request ^^

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
