### ISSUE TITLE
Overriding HttpServer::MAXIMUM_BUFFER_SIZE

### ISSUE THREAD

**Issue by Hast** [reactphp/http#436]
Hello. I just upgraded from 0.8.7 to 1.5.0. Before the upgrade, we could accept requests up to 10MB. But now all the requests are always being cut. The problem is that `LimitConcurrentRequestsMiddleware` used to operate INI's `post_max_size` settings, and now it's limited by `HttpServer::getMaxRequestSize()`, and its result can not be higher than `HttpServer::MAXIMUM_BUFFER_SIZE`. Is there any workaround to accept heavy packages?

RequestBodyBufferMiddleware has a solution for this (it ignores sizeLimit if an actual size is higher):
```
        // request body of known size exceeding limit
        $sizeLimit = $this->sizeLimit;
        if ($size > $this->sizeLimit) {
            $sizeLimit = 0;
        }
```

But `LimitConcurrentRequestsMiddleware` is always being limited to MAXIMUM_BUFFER_SIZE.

I find the logic pretty unclear, because `RequestBodyBufferMiddleware` does accept packages higher than MAXIMUM_BUFFER_SIZE, but at the same time it's always limited due to `LimitConcurrentRequestsMiddleware`.

**Comment by Hast** [comment]
Fixed by explicitly passing middleware objects to HttpServer:

```
        $requestMaxSize = $this->iniSizeToBytes($this->requestMaxSize);
        $memoryLimit = $this->iniSizeToBytes($this->memoryLimit);

        $requestHandlers = [];
        $requestHandlers[] = new StreamingRequestMiddleware();

        $concurrency = $this->getConcurrentRequestsLimit($memoryLimit, $requestMaxSize);
        if ($concurrency !== null) {
            $requestHandlers[] = new LimitConcurrentRequestsMiddleware($concurrency);
        }

        $requestHandlers[] = new RequestBodyBufferMiddleware($requestMaxSize);
        if ($this->enablePostDataReading) {
            $requestHandlers[] = new RequestBodyParserMiddleware();
        }

        return new React\Http\HttpServer(
            ...$requestHandlers,
            $callback
        );
```

**Comment by SimonFrings** [comment]
Hey @Hast, thanks for opening this up :+1: 

It seems like you already found your way of dealing with this, a similar approach can be found inside the [documentation](https://github.com/reactphp/http#httpserver). You can also take a look at #371.
