### ISSUE TITLE
HttpServer promise cancellation

### ISSUE THREAD

**Issue by bileslaw** [reactphp/http#443]
Hi there,

I know that `HttpServer` cancels the promise returned to it if the connection is closed prematurely.

My app streams large files using `Browser`, so logically this is very useful for me,
but here comes the difficulty when using [react/async](https://github.com/reactphp/async), since there's no cancellation.

It's quite hard for me to change the flow to make it work (it would be a mixture of async/await and promises), nevertheless,
there's such a possibility. Should I take care of this? Or will streaming be terminated when the connection is closed anyway?

I tried to make artificial test, but I didn't succeed to understand.
Here's a super simplified example of how it's done for me now:

```php
$responder = function (ServerRequestInterface $request) use ($browser): ResponseInterface {
	return await($browser->requestStreaming('GET', '...'));
};

$server = new HttpServer(async($responder));
```

**Comment by WyriHaximus** [comment]
This PR might interest you https://github.com/reactphp/async/pull/20 as it brings cancellation to `async` and `await` (inside `async`).
