### ISSUE TITLE
is React\Http\Message\Response::plaintext binary safe? how am i supposed to respond with binary data?

### ISSUE THREAD

**Issue by divinity76** [reactphp/http#447]
lets say i want to respond "\x06\x00\xFF\xFFinfo" , how am i supposed to do that? 
seems the documentation is not clear on whether  or not "Response::plaintext()" is binary-safe or not, and how one is supposed to respond with binary data..?

**Comment by divinity76** [comment]
nvm, yes it is binary safe.

**Comment by clue** [comment]
@divinity76 Interesting question!

The `plaintext()` method expects a valid Unicode string encoded as UTF-8, as per the documentation: https://github.com/reactphp/http#plaintext

The string `\x06\x00\xFF\xFFinfo` is not valid UTF-8, so you probably shouldn't be using this method. The method itself is binary safe, but only guarantees to accept valid UTF-8. Future versions may reject and/or replace invalid UTF-8.

As per the documentation, you can always create a custom HTTP response like this:

```php
$response = new React\Http\Message\Response(
    React\Http\Message\Response::STATUS_OK,
    [
//      'Content-Type' => '???'
    ],
    "\x06\x00\xFF\xFFinfo"
);
```

I hope this helps! :+1:
