### ISSUE TITLE
Server: header size exceeded when streaming request

### ISSUE THREAD

**Issue by bartvanhoutte** [reactphp/http#456]
👋 When streaming a large request (7MB jpg) I get the following error: `OverflowException: Maximum header size of 8192 exceeded. in /opt/project/vendor/react/http/src/Io/RequestHeaderParser.php:43`.

The error can be reproduced with the following snippet:

```php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use React\Http\HttpServer;
use React\Http\Message\Response;
use React\Http\Middleware\StreamingRequestMiddleware;
use React\Socket\SocketServer;

$server = new HttpServer(
  new StreamingRequestMiddleware,
  fn() => new Response
);

$server->on('error', function (Throwable $t) {
    fwrite(STDERR, (string)$t);
});

$socket = new SocketServer('0.0.0.0:8080');
$server->listen($socket);
```

I'm using `react/http 1.6.0`.

I'm trying to understand what goes on behind the curtain but can't quite figure it out. The listener that handles data coming from the connection should be removed in the `RequestHeaderParser` but since a new instance of the parser is made whenever data comes in from the connection the error is thrown.

**Comment by bartvanhoutte** [comment]
Aaah, this is probably because I'm not waiting for the request stream to close which means the remaining incoming data will be viewed as a new request!

**Comment by bartvanhoutte** [comment]
@clue If the above is correct, would you like me to file a PR to improve documentation?

**Comment by clue** [comment]
> Aaah, this is probably because I'm not waiting for the request stream to close which means the remaining incoming data will be viewed as a new request!

@bartvanhoutte Yes, this appears to be what's going on. I agree that depending on how you look at it, it could be seen as a feature request or bug or simply lack of documentation. If you find a way to improve this, we definitely welcome PRs! :shipit: 

That said, it looks like you ran into this while looking for better ways to handle (large) file uploads. This is something I'm currently working on and definitely something we should improve! (see also https://github.com/reactphp/http/issues/428, https://github.com/clue/framework-x/discussions/69 and others)
