### ISSUE TITLE
Exemple of requestStreaming() with request AND response non blocking streaming 

### ISSUE THREAD

**Issue by quazardous** [reactphp/http#463]
Can someone provide an exemple of stream request chain/pipe with an HTTP server using `requestStreaming` (?)

**Comment by quazardous** [comment]
I mean i'm working on a non blocking feed API that can stream process a feed. But I'm not sure the actual browser is able to upload a feed requet while starting to stream download the response.

**Comment by SimonFrings** [comment]
Hey @quazardous

You can take a look at the [streaming request](https://github.com/reactphp/http#streaming-request) and the [streaming response](https://github.com/reactphp/http#streaming-response) chapter inside our documentation.

Does this help to get you started?

**Comment by quazardous** [comment]
thx, I did a mix of the 2

```php

     $browser->requestStreaming($method, $url, $headers, $body)->then(function (ResponseInterface $response) use ($processItem, &$l, &$res) {

            $res = $response;
            $body = $response->getBody();
            if ($body instanceof ReadableStreamInterface) {
                $in = new \Clue\React\NDJson\Decoder($body);

                $in->on('data', function ($data) use ($processItem, &$l) {
                    ++$l;
                    // $data = \json_decode($data);
                    \call_user_func_array($processItem, [$data]);
                });

                $body->on('error', function (\Exception $e) {
                    echo 'Error: ' . $e->getMessage() . PHP_EOL;
                });

                $body->on('close', function () {
                    echo '[DONE]' . PHP_EOL;
                });
            } else {
                throw new \LogicException("D'oh!?");
            }
        }, function (\RuntimeException $reason) {
            echo "REJECTED\n";
            echo $reason->getMessage();
        }, function ($data) {
            echo "Progress: " . \get_class($data);
        });

        // important !
        $loop->run();

```

In fact I had a problem on the server part.

I'm sharing it.

The server (written with react http) has a read timeout feature on the connection stream (to drop inactives requests). And in some case when the stream chain is taking too much time the read timeout is triggered even though there is data in the output/write queue waiting to be send back to the browser/client.

It's because the timers are checked BEFORE streams/events in `$loop->run()`. So the read timeout was triggered before the data stream/event that was cancelling the timeout...

So the workaround was to use a double timer (timer of timer) to allow the events to have one more loop to be triggered.

It's not perfect because the timeout is not always respected due to the internal stream chain proccess but at least it's working !

great job BTW with reactphp. this is an amazing piece of code !!

**Comment by SimonFrings** [comment]
@quazardous Glad you like the project 👍

I made similar experiences. Always keep in mind that your code doesn't need to be perfect right away, first make it work and then polish the details.

**Comment by clue** [comment]
I believe this has been answered, good progress! Please come back with more details if this problem persists and we can always reopen this :+1:
