### ISSUE TITLE
Header names are not case-sensitive

### ISSUE THREAD

**Issue by marcj** [reactphp/http#51]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

`Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive`

Currently the [code](https://github.com/reactphp/http/blob/master/src/RequestParser.php#L67) [heavily](https://github.com/reactphp/http/blob/master/src/RequestParser.php#L127) relies on case-sensitive names.

Also Content-Type can contain a charset or additional information after `;` character. Example: `Content-Type: application/x-www-form-urlencoded; charset=utf-8` Such header break currently content parsing because of [this](https://github.com/reactphp/http/blob/master/src/RequestParser.php#L141).

We tried to fix it in PPM: https://github.com/php-pm/php-pm/blob/master/React/RequestParser.php#L18, but I believe we should fix it directly in reactphp/http.

**Comment by WyriHaximus** [comment]
Thanks for reporting and you're absolutely right, this has been on my mind for a while. I'm in favor of `strtolower` all the header names. 

@clue what is your take on this?

**Comment by WyriHaximus** [comment]
Or could go for a class that behaves as an array and makes them case-insensitive

**Comment by clue** [comment]
> but I believe we should fix it directly in reactphp/http

Absolutely! :+1:

Afaict *most* occurrences will be replaced with PR #41 anyway, but we should definitely keep an eye on this.

> I'm in favor of strtolower all the header names. 

Yeah, this should do it for now (http://php.net/array_change_key_case).

Eventually we will look into supporting PSR-7 (#28), by then we will also follow proper message semantics while preserving header case information.

FWIW, RFC 2616 has been replaced with this:
> Each header field consists of a case-insensitive field name followed by […]
> http://tools.ietf.org/html/rfc7230#section-3.2

**Comment by pwhelan** [comment]
I actually went ahead and implemented a fix in PR #53 since I needed a fix for a work project. Hopefully #41 gets merged soon so I can drop my fix.

**Comment by andig** [comment]
Will we ever see #41? It's a year in making now (sad).

**Comment by WyriHaximus** [comment]
@andig It's nearing completion see https://github.com/reactphp/http/pull/41#issuecomment-252432624 see the issues mentioned in that comment. You're input on those is valued :+1:

**Comment by clue** [comment]
I'm currently looking into this and will file a PR for the upcoming v0.4.4 release. See #103 for the first step here.
