### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by marcj** [reactphp/http#52]
Could you guys tag a new version with the current state? We at php-pm need the [new MultipartParser](https://github.com/reactphp/http/compare/v0.4.1...master#diff-f89b2249e75bdd48a3f00cf35b607d8c) :)

**Comment by WyriHaximus** [comment]
We're working on completing the work on MultipartParser in #41. The current state doesn't work well with large requests :(.

**Comment by WyriHaximus** [comment]
Let me add that I'm planning to spend most of my day on #41 tomorrow to get this done A.S.A.P.

**Comment by marcj** [comment]
Very very nice @WyriHaximus! Let me know if I can support you somewhere.

**Comment by WyriHaximus** [comment]
Will do @marcj, I'll get the todos checked off and ping you to test them in php-pm :).

**Comment by clue** [comment]
Thanks for filing this ticket, I can assure you we're working hard on this :+1: 

This ticket currently targets an unstable development feature, so I've just filed #105 to keep track of the underlying feature request here. Please bear with us, we'll keep this ticket updated :+1:
