### ISSUE TITLE
Warning: unable to shutdown socket

### ISSUE THREAD

**Issue by Vahanerevan** [reactphp/http#55]
When I close browser tab.

I get log.
Warning: unable to shutdown socket [57]: Socket is not connected in /Users/vahan/Development/tcp-server/vendor/react/socket/src/Connection.php on line 27

**Comment by WyriHaximus** [comment]
Is this something you can reproduce each time? What browser and version are you using?

**Comment by Vahanerevan** [comment]
Latest http . pull 2 days ago (I know its unstable but gives me 6ms per request :) it's awesome).
Chrome Version 49.0.2623.87 (64-bit)
Mac OS
HHVM - HipHop VM 3.11.0 (rel)

**Comment by Vahanerevan** [comment]
Tested with curl it's OK.

Opear,Safary, same issue .
I think browser tries to keep alive then something goes wrong.

**Comment by Vahanerevan** [comment]
curl --keepalive-time 60 --keepalive http://localhost:8789/url.hh GOT ISSUE

curl  http://localhost:8789/url.hh  Everything is fine.

**Comment by WyriHaximus** [comment]
Thanks for the info. Can I reproduce this with `curl --keepalive-time 60 --keepalive http://localhost:8789/url.hh` against the example in the readme?

Also the unstable part refers more to the lack of certain features we're working on :).

**Comment by Vahanerevan** [comment]
Yes I use same code as in example. 
Just run the example and do curl with keep alive.
Only I use hhvm not php if it matter (but I don't think there is difference for react).

**Comment by WyriHaximus** [comment]
Will run some tests first before ruling anything out.

**Comment by clue** [comment]
I believe this has been fixed, so I'll close this for now. If the problem persists, please come back with more details and we can reopen this :+1:
