### ISSUE TITLE
RequestParser vanished

### ISSUE THREAD

**Issue by szepeviktor** [reactphp/http#60]
Good afternoon!
This commit https://github.com/reactphp/http/commit/a2bad36f1438f2420ce1ddc5c7fdccea14f0bd61
introduced src/RequestParser.php
two commits after this  in master https://github.com/reactphp/http/tree/56ea21e71d8e07944749183c4946405e73dd82e9/src
src/RequestParser.php vanishes.

Please advise.

**Comment by szepeviktor** [comment]
I see you are reverting things...
`git checkout cd15204bd15d106d7832c680e4fb0ca0ce2f5e30` and OK!

**Comment by WyriHaximus** [comment]
Hey @szepeviktor for now you can target `dev-streaming-multipart` instead of `dev-master`. `dev-streaming-multipart` has the request parser and is pretty close to what the next tag is going to be like.
