### ISSUE TITLE
Where are POST data? It dissappeared, but ... where and why?

### ISSUE THREAD

**Issue by visitek** [reactphp/http#61]

**Comment by WyriHaximus** [comment]
We reverted some commits removing license incompatible code in #59. It will return in a different form when #41 is chopped up in different PR's and merged. For now you can target `dev-streaming-multipart` instead of `dev-master` until those changes are in.

**Comment by visitek** [comment]
WTF? :D :D

**Comment by WyriHaximus** [comment]
Read up on #41 and target `dev-streaming-multipart` for now, I'll ping you here when that PR is chopped up, in master, and tagged for release :smile: .

**Comment by visitek** [comment]
we use "react/http": "dev-master#cd15204bd15d106d7832c680e4fb0ca0ce2f5e30",

**Comment by WyriHaximus** [comment]
That also work's :+1:

**Comment by clue** [comment]
Thanks for filing this ticket, I can assure you we're working hard on this :+1: 

This ticket currently targets an unstable development branch, so I've just filed #105 to keep track of the underlying feature request here. Please bear with us, we'll keep this ticket updated :+1:
