### ISSUE TITLE
stop server but continue loop

### ISSUE THREAD

**Issue by demil** [reactphp/http#74]
Is it possible to stop server, but continue main loop?

I am trying with        

            $this->socket->shutdown();

but it ends whole script.

**Comment by clue** [comment]
The loop keeps running while it has anything to do.

Shutting down the server socket will only stop listening for new connections. Any existing open connections will be kept open.

Once the last connection is closed and no new connections are allowed, there's nothing for the loop to do. What would you want it to do anyway?

I hope this helps :+1:

**Comment by demil** [comment]
I want to stop http server to accept connections but loop should continue to do cronjobs etc, and when i stop http server i would implement timer to restart it in some period of time.

but when i call

      $this->socket->shutdown();

whole script goes down.

**Comment by clue** [comment]
The loop keeps running while it has anything to do.

If you want to continue working with the loop, you may want to set up a timer which then starts a new socket server instance.

I have to admit your use case is a bit unclear to me, perhaps you can elaborate or share a gist?
