### ISSUE TITLE
Header Problems

### ISSUE THREAD

**Issue by geggleto** [reactphp/http#77]
**Problem:** 
Array to String Converstion

**Description:**
PSR-7 dictates the format of the Headers as a key with a collection of header-lines.

**Offending Code:**
https://github.com/reactphp/http/blob/master/src/Response.php#L85

**Reproducible:** 
Yes

**Context:**
I was attempting to bridge Slim's PSR-7 HTTP objects into React.

**Code:**
```php

    try {
        /** @var $slimResponse  Response */
        $slimResponse = $slim($slimRequest, new Response());

        //This below line constructs the React Response with Slim Data
        $response->writeHead($slimResponse->getStatusCode(), $slimResponse->getHeaders());
        $slimResponse->getBody()->rewind();
        $response->end($slimResponse->getBody()->getContents());
    } catch (Exception $e) {
        $response->writeHead(500, array('Content-Type' => 'text/html'));
        $response->end('Internal Server Error');
    }

```

**Comment by clue** [comment]
You may want to iterate over your PSR-7 headers and remove one nesting depth so that it's compatible with React's headers. We should probably eventually implement PSR-7, see also #28.

**Comment by geggleto** [comment]
I did manage to get it to work finally :)

https://github.com/geggleto/slim-service-registry/blob/master/app.php

**Comment by clue** [comment]
Thanks for reporting back and glad you've got this sorted! :+1: 

I'll assume this is resolved and will close this for now, please feel free to report back otherwise.

**Comment by geggleto** [comment]
All is good... only suggestion is to hurry up with PSR-7 :P

**Comment by cboden** [comment]
Pull requests welcome :)
