### ISSUE TITLE
Provide Interfaces

### ISSUE THREAD

**Issue by geggleto** [reactphp/http#78]
Would you be open to programming React Against a set of interfaces?

That way I can use other PSR-7 HTTP and embed the react interface in an extension of an already existing PSR-7 http object.

**Comment by clue** [comment]
What kind of interfaces are you looking for? IMO we should focus our efforts on providing native PSR-7 support (see #28) instead of providing our own set of interfaces.

**Comment by WyriHaximus** [comment]
Honestly I think PSR-7 is the way to go, you've done great work coming up with solutions regarding that on the client side @clue :+1:

**Comment by clue** [comment]
I believe this has been answered, see #28 for more details.

I'll close this for now, please come back with more details if this problem persists and we can reopen this :+1:
