### ISSUE TITLE
Question: What is the right way to send huge content or live stream content?

### ISSUE THREAD

**Issue by thestanislav** [reactphp/http#79]
Seem above code does not work as I expect.
How can force flush the content to the browser.

```php
$loop = React\EventLoop\Factory::create();
$socket = new React\Socket\Server($loop);

$http = new React\Http\Server($socket);
$http->on('request', function ($request, $response) {
    $response->writeHead(200, array('Content-Type' => 'video/mp4'));
    $fp = fopen('Path/to/some/real/big/video.mp4', 'r');
    while (!feof($fp)) {
        $response->write(fread($fp, 1024 * 10));
    }
    fclose($fp);

    $response->end();
});

$socket->listen(1337);
$loop->run();
```

**Comment by arunpoudel** [comment]
You can probably do a `$loop->tick()` to force it to process the buffer.

**Comment by thestanislav** [comment]
But after some time I have got this:
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 65393860 bytes) in vendor/react/stream/src/Buffer.php on line 118

**Comment by clue** [comment]
Hi @thestanislav, thanks for your question! What you're looking for is *piping* a source stream into the destination like this:

```php
$source = new Stream($fp, $loop);
$source->pipe($response);
```

This controls back-pressure internally: It will make sure the `$source` will be `pause()`'d when the destination is not fast enough and starts buffering. It will automatically `resume()` reading from the `$source` once the buffer is drained.

I hope this helps :+1: 

Note: The filesystem is inherently blocking, so it's best to avoid any `fopen()` calls to begin with. But you *may* get away with this like this.

**Comment by thestanislav** [comment]
Hi, @clue . Can you help me with more descriptive example?
```php
$http->on('request', function ($request, $response)  use($loop)  {
    $response->writeHead(200, array('Content-Type' => 'video/mp4'));
    $fp = fopen('Path/to/some/real/big/video.mp4', 'r');
    
    $source = new Stream($fp, $loop);
    $source->pipe($response);

    fclose($fp);
    $response->end();
});
```

What I am missing?

**Comment by clue** [comment]
The `Stream` will close the resource for you once it ends, so you should remove this:

```diff
-fclose($fp);
```

**Comment by thestanislav** [comment]
Same thing. 
I'm getting zero length response :(

**Comment by thestanislav** [comment]
After some debug I found out that Stream::handleData is never called.

**Comment by thestanislav** [comment]
_$loop->run()_ helped. Not sure this is a right way.

```php
$http->on('request', function ($request, $response)  use($loop)  {
    $response->writeHead(200, array('Content-Type' => 'video/mp4'));
    $fp = fopen('Path/to/some/real/big/video.mp4', 'r');

    $source = new Stream($fp, $loop);
    $source->pipe($response);
    $loop->run();

    fclose($fp);
    $response->end();
});
```

**Comment by WyriHaximus** [comment]
Try this:

```php
$http->on('request', function ($request, $response)  use($loop)  {
    $response->writeHead(200, array('Content-Type' => 'video/mp4'));
    $fp = fopen('Path/to/some/real/big/video.mp4', 'r');

    $source = new Stream($fp, $loop);
    $source->pipe($response);
});
```

When calling `$response->end();` the entire response stream is closed. `$source->pipe($response);` will do that for you once the file has been completely read and piped into the response.
