### ISSUE TITLE
Latest change to reactphp/stream broken header parser

### ISSUE THREAD

**Issue by nick4fake** [reactphp/http#80]
Hi,

Please note, that RequestHeaderParser has maxSize around 4096. It does not work with latest react streams as there is a high chance the first buffer would be longer, than 4096 bytes

**Comment by WyriHaximus** [comment]
@nick4fake good catch, would you mind making a PR fixing that?

**Comment by nick4fake** [comment]
@WyriHaximus yes, doing that right now. :)

**Comment by WyriHaximus** [comment]
Awesome :+1:

**Comment by clue** [comment]
Closed via #88
