### ISSUE TITLE
Pause/resume on request not working

### ISSUE THREAD

**Issue by nick4fake** [reactphp/http#84]
Hi,

Why do we have this code in Server class?
````
$request->on('pause', function () use ($conn) {
    $conn->emit('pause');
});
$request->on('resume', function () use ($conn) {
    $conn->emit('resume');
});
````

I have changed emit's to correct methods (pause/resume), like this:
````
$request->on('pause', function () use ($conn) {
    $conn->pause();
});
$request->on('resume', function () use ($conn) {
    $conn->resume();
});
````

And now pausing works.

**Comment by clue** [comment]
Thanks for reporting! Do you feel like filing a PR and adding some tests to verify this? Thanks! :+1:

**Comment by nick4fake** [comment]
@clue Ok, will do that tomorrow

**Comment by nick4fake** [comment]
@clue sorry for delaying the fix. Created pull review.

Is there any roadmap for merging all those pull request? There are 25 PRs now.
